<?php
/**
 * Outward-code profiles for every town in data/areas.json.
 * District strings are unique even after the town name is removed,
 * so town-swap doorway pages cannot share a meta or FAQ.
 * Postcode districts are the published Royal Mail outward codes for that
 * place. This file does not claim drive times.
 */
return [
    'Manchester' => ['districts' => 'M1–M40', 'region' => 'Greater Manchester', 'stock' => 'city-centre flats, Victorian terraces and multi-let offices', 'focus' => 'high-rise residential and city commercial'],
    'Salford' => ['districts' => 'M3, M5–M7 and M50', 'region' => 'Greater Manchester', 'stock' => 'quayside apartments, older terraces and industrial estates', 'focus' => 'mixed-use blocks and media-city offices'],
    'Bolton' => ['districts' => 'BL1–BL7', 'region' => 'Greater Manchester', 'stock' => 'terraced housing, converted mills and retail parks', 'focus' => 'landlord portfolios and light industry'],
    'Bury' => ['districts' => 'BL8–BL9', 'region' => 'Greater Manchester', 'stock' => 'suburban housing, town retail and light industry', 'focus' => 'high-street commercial and housing'],
    'Oldham' => ['districts' => 'OL1–OL4 and OL8–OL9', 'region' => 'Greater Manchester', 'stock' => 'terraced streets, mill buildings and industrial estates', 'focus' => 'residential portfolios and warehouse units'],
    'Rochdale' => ['districts' => 'OL11–OL12', 'region' => 'Greater Manchester', 'stock' => 'town housing, retail and edge-of-town industry', 'focus' => 'agents and SME sites'],
    'Stockport' => ['districts' => 'SK1–SK4 and SK5–SK8', 'region' => 'Greater Manchester', 'stock' => 'suburban housing, town-centre retail and industrial units', 'focus' => 'landlord portfolios from the SK2 base'],
    'Wigan' => ['districts' => 'WN1–WN3', 'region' => 'Greater Manchester', 'stock' => 'housing estates, town retail and industrial corridors', 'focus' => 'multi-site commercial'],
    'Leigh' => ['districts' => 'WN7', 'region' => 'Greater Manchester', 'stock' => 'town housing and industrial estates', 'focus' => 'commercial and landlord stock'],
    'Atherton' => ['districts' => 'M46', 'region' => 'Greater Manchester', 'stock' => 'former mining terraces and local retail', 'focus' => 'small commercial and housing'],
    'Tyldesley' => ['districts' => 'M29', 'region' => 'Greater Manchester', 'stock' => 'town terraces and local shops', 'focus' => 'housing and small commercial'],
    'Horwich' => ['districts' => 'BL6', 'region' => 'Greater Manchester', 'stock' => 'suburban housing and the Rivington fringe', 'focus' => 'residential and small commercial'],
    'Westhoughton' => ['districts' => 'BL5', 'region' => 'Greater Manchester', 'stock' => 'town housing and local industrial units', 'focus' => 'housing and workshops'],
    'Farnworth' => ['districts' => 'BL4 west of the town centre', 'region' => 'Greater Manchester', 'stock' => 'dense terraces and local retail', 'focus' => 'landlord housing'],
    'Kearsley' => ['districts' => 'BL4 along the Irwell', 'region' => 'Greater Manchester', 'stock' => 'terraces and small industrial sites', 'focus' => 'housing and workshops'],
    'Little Lever' => ['districts' => 'BL3', 'region' => 'Greater Manchester', 'stock' => 'village housing and local shops', 'focus' => 'residential'],
    'Radcliffe' => ['districts' => 'M26', 'region' => 'Greater Manchester', 'stock' => 'town housing and canalside commercial', 'focus' => 'housing and small commercial'],
    'Whitefield' => ['districts' => 'M45', 'region' => 'Greater Manchester', 'stock' => 'suburban semis and local parade shops', 'focus' => 'residential'],
    'Prestwich' => ['districts' => 'M25', 'region' => 'Greater Manchester', 'stock' => 'suburban housing and high-street retail', 'focus' => 'residential and shops'],
    'Swinton' => ['districts' => 'M27 civic centre', 'region' => 'Greater Manchester', 'stock' => 'suburban housing and civic commercial', 'focus' => 'housing and offices'],
    'Eccles' => ['districts' => 'M30', 'region' => 'Greater Manchester', 'stock' => 'suburban housing and industrial edges', 'focus' => 'residential and light industry'],
    'Walkden' => ['districts' => 'M28 shopping centre', 'region' => 'Greater Manchester', 'stock' => 'suburban housing and retail sheds', 'focus' => 'housing and retail'],
    'Worsley' => ['districts' => 'M28 green-belt edge', 'region' => 'Greater Manchester', 'stock' => 'lower-density housing and small offices', 'focus' => 'residential'],
    'Pendlebury' => ['districts' => 'M27 industrial edge', 'region' => 'Greater Manchester', 'stock' => 'terraces and industrial units', 'focus' => 'housing and workshops'],
    'Irlam' => ['districts' => 'M44 station side', 'region' => 'Greater Manchester', 'stock' => 'housing estates and local industry', 'focus' => 'residential and industrial'],
    'Cadishead' => ['districts' => 'M44 towards the ship canal', 'region' => 'Greater Manchester', 'stock' => 'housing and canalside industry', 'focus' => 'residential and industrial'],
    'Altrincham' => ['districts' => 'WA14–WA15', 'region' => 'Greater Manchester', 'stock' => 'market-town retail and suburban housing', 'focus' => 'offices and residential'],
    'Sale' => ['districts' => 'M33', 'region' => 'Greater Manchester', 'stock' => 'suburban housing and local retail', 'focus' => 'landlords and small commercial'],
    'Stretford' => ['districts' => 'M32', 'region' => 'Greater Manchester', 'stock' => 'housing, mall retail and industrial edges', 'focus' => 'retail and residential'],
    'Urmston' => ['districts' => 'M41', 'region' => 'Greater Manchester', 'stock' => 'suburban housing and town retail', 'focus' => 'residential'],
    'Chorlton' => ['districts' => 'M21', 'region' => 'Greater Manchester', 'stock' => 'terraces, apartments and independent retail', 'focus' => 'residential portfolios'],
    'Didsbury' => ['districts' => 'M20 village and west', 'region' => 'Greater Manchester', 'stock' => 'period houses, apartments and high-street retail', 'focus' => 'landlord apartments'],
    'Withington' => ['districts' => 'M20 hospital district', 'region' => 'Greater Manchester', 'stock' => 'student HMOs and terraced housing', 'focus' => 'HMO stock'],
    'Wythenshawe' => ['districts' => 'M22–M23', 'region' => 'Greater Manchester', 'stock' => 'estate housing, retail and industrial units', 'focus' => 'housing and commercial'],
    'Cheadle' => ['districts' => 'SK8 village', 'region' => 'Greater Manchester', 'stock' => 'suburban housing and village retail', 'focus' => 'residential'],
    'Cheadle Hulme' => ['districts' => 'SK8 station district', 'region' => 'Greater Manchester', 'stock' => 'suburban housing and local shops', 'focus' => 'residential'],
    'Bramhall' => ['districts' => 'SK7 park side', 'region' => 'Greater Manchester', 'stock' => 'lower-density housing and village retail', 'focus' => 'residential'],
    'Hazel Grove' => ['districts' => 'SK7 A6 corridor', 'region' => 'Greater Manchester', 'stock' => 'suburban housing and parade shops', 'focus' => 'residential'],
    'Marple' => ['districts' => 'SK6 canal town', 'region' => 'Greater Manchester', 'stock' => 'stone housing and village retail', 'focus' => 'residential'],
    'Romiley' => ['districts' => 'SK6 railway side', 'region' => 'Greater Manchester', 'stock' => 'suburban housing and local shops', 'focus' => 'residential'],
    'Hyde' => ['districts' => 'SK14', 'region' => 'Greater Manchester', 'stock' => 'terraces, town retail and industrial estates', 'focus' => 'housing and industry'],
    'Stalybridge' => ['districts' => 'SK15', 'region' => 'Greater Manchester', 'stock' => 'canal-town housing and mills', 'focus' => 'housing and small industrial'],
    'Dukinfield' => ['districts' => 'SK16', 'region' => 'Greater Manchester', 'stock' => 'terraces and industrial units', 'focus' => 'housing and workshops'],
    'Ashton-under-Lyne' => ['districts' => 'OL6–OL7', 'region' => 'Greater Manchester', 'stock' => 'town-centre retail, market and terraces', 'focus' => 'commercial and housing'],
    'Mossley' => ['districts' => 'OL5', 'region' => 'Greater Manchester', 'stock' => 'hillside stone terraces and mills', 'focus' => 'housing'],
    'Droylsden' => ['districts' => 'M43', 'region' => 'Greater Manchester', 'stock' => 'suburban housing and local retail', 'focus' => 'residential'],
    'Denton' => ['districts' => 'M34', 'region' => 'Greater Manchester', 'stock' => 'housing estates and industrial units', 'focus' => 'residential and industry'],
    'Failsworth' => ['districts' => 'M35', 'region' => 'Greater Manchester', 'stock' => 'suburban housing and the A62 shops', 'focus' => 'residential'],
    'Middleton' => ['districts' => 'M24', 'region' => 'Greater Manchester', 'stock' => 'town housing, retail and industrial estates', 'focus' => 'housing and commercial'],
    'Chadderton' => ['districts' => 'OL9', 'region' => 'Greater Manchester', 'stock' => 'suburban housing and industrial estates', 'focus' => 'housing and industry'],
    'Heywood' => ['districts' => 'OL10', 'region' => 'Greater Manchester', 'stock' => 'town housing and industrial estates', 'focus' => 'housing and industry'],
    'Milnrow' => ['districts' => 'OL16 east of the town', 'region' => 'Greater Manchester', 'stock' => 'housing and small industrial units', 'focus' => 'residential'],
    'Littleborough' => ['districts' => 'OL15', 'region' => 'Greater Manchester', 'stock' => 'stone housing on the Pennine edge', 'focus' => 'residential'],
    'Shaw' => ['districts' => 'OL2 west', 'region' => 'Greater Manchester', 'stock' => 'town housing and local shops', 'focus' => 'residential'],
    'Royton' => ['districts' => 'OL2 east', 'region' => 'Greater Manchester', 'stock' => 'suburban housing and local retail', 'focus' => 'residential'],
    'Lees' => ['districts' => 'OL4', 'region' => 'Greater Manchester', 'stock' => 'village housing and local shops', 'focus' => 'residential'],
    'Uppermill' => ['districts' => 'OL3 village', 'region' => 'Greater Manchester', 'stock' => 'stone village housing and tourism retail', 'focus' => 'village commercial'],
    'Saddleworth' => ['districts' => 'OL3 valleys', 'region' => 'Greater Manchester', 'stock' => 'scattered stone villages and small commercial', 'focus' => 'village property'],
    'Liverpool' => ['districts' => 'L1–L25', 'region' => 'Merseyside', 'stock' => 'city apartments, terraces, docks commercial and retail', 'focus' => 'HMOs, offices and hospitality'],
    'Birkenhead' => ['districts' => 'CH41–CH42', 'region' => 'Merseyside', 'stock' => 'terraced housing, docks and retail', 'focus' => 'residential and commercial'],
    'Wallasey' => ['districts' => 'CH44–CH45', 'region' => 'Merseyside', 'stock' => 'coastal housing and local retail', 'focus' => 'residential'],
    'Bebington' => ['districts' => 'CH63', 'region' => 'Merseyside', 'stock' => 'suburban housing and village retail', 'focus' => 'residential'],
    'Heswall' => ['districts' => 'CH60', 'region' => 'Merseyside', 'stock' => 'lower-density housing and village shops', 'focus' => 'residential'],
    'West Kirby' => ['districts' => 'CH48', 'region' => 'Merseyside', 'stock' => 'coastal housing and local retail', 'focus' => 'residential'],
    'Hoylake' => ['districts' => 'CH47', 'region' => 'Merseyside', 'stock' => 'coastal housing and small commercial', 'focus' => 'residential'],
    'Bootle' => ['districts' => 'L20 and L30', 'region' => 'Merseyside', 'stock' => 'terraces, docks and retail', 'focus' => 'residential and commercial'],
    'Crosby' => ['districts' => 'L23', 'region' => 'Merseyside', 'stock' => 'suburban and coastal housing', 'focus' => 'residential'],
    'Maghull' => ['districts' => 'L31', 'region' => 'Merseyside', 'stock' => 'suburban housing and town retail', 'focus' => 'residential'],
    'Formby' => ['districts' => 'L37', 'region' => 'Merseyside', 'stock' => 'coastal suburban housing', 'focus' => 'residential'],
    'Ainsdale' => ['districts' => 'PR8 coastal', 'region' => 'Merseyside', 'stock' => 'coastal housing and local shops', 'focus' => 'residential'],
    'Southport' => ['districts' => 'PR8–PR9', 'region' => 'Merseyside', 'stock' => 'Victorian housing, guest accommodation and retail', 'focus' => 'hospitality and residential'],
    'Ormskirk' => ['districts' => 'L39', 'region' => 'Lancashire', 'stock' => 'market-town housing and retail', 'focus' => 'town commercial and housing'],
    'Burscough' => ['districts' => 'L40', 'region' => 'Lancashire', 'stock' => 'village housing and industrial estates', 'focus' => 'housing and industry'],
    'Skelmersdale' => ['districts' => 'WN8', 'region' => 'Lancashire', 'stock' => 'new-town housing and industrial estates', 'focus' => 'housing and industry'],
    'Rainford' => ['districts' => 'WA11 rural', 'region' => 'Merseyside', 'stock' => 'village housing and small workshops', 'focus' => 'residential'],
    'Prescot' => ['districts' => 'L34', 'region' => 'Merseyside', 'stock' => 'town housing and retail', 'focus' => 'residential and shops'],
    'Whiston' => ['districts' => 'L35 hospital district', 'region' => 'Merseyside', 'stock' => 'housing estates and local shops', 'focus' => 'residential'],
    'Rainhill' => ['districts' => 'L35 village', 'region' => 'Merseyside', 'stock' => 'village housing and local shops', 'focus' => 'residential'],
    'St Helens' => ['districts' => 'WA9–WA10', 'region' => 'Merseyside', 'stock' => 'town housing and industrial corridors', 'focus' => 'commercial and housing'],
    'Haydock' => ['districts' => 'WA11 industrial', 'region' => 'Merseyside', 'stock' => 'housing and distribution estates', 'focus' => 'industrial and housing'],
    'Newton-le-Willows' => ['districts' => 'WA12', 'region' => 'Merseyside', 'stock' => 'town housing and local industry', 'focus' => 'residential and commercial'],
    'Golborne' => ['districts' => 'WA3 town', 'region' => 'Greater Manchester', 'stock' => 'town housing and local shops', 'focus' => 'residential'],
    'Ashton-in-Makerfield' => ['districts' => 'WN4', 'region' => 'Greater Manchester', 'stock' => 'town housing and local retail', 'focus' => 'residential'],
    'Hindley' => ['districts' => 'WN2', 'region' => 'Greater Manchester', 'stock' => 'terraces and local shops', 'focus' => 'residential'],
    'Ince' => ['districts' => 'WN1–WN2 industrial', 'region' => 'Greater Manchester', 'stock' => 'terraces and industrial land', 'focus' => 'housing and industry'],
    'Standish' => ['districts' => 'WN6 crossroads', 'region' => 'Greater Manchester', 'stock' => 'village housing and local shops', 'focus' => 'residential'],
    'Shevington' => ['districts' => 'WN6 west', 'region' => 'Greater Manchester', 'stock' => 'village housing', 'focus' => 'residential'],
    'Preston' => ['districts' => 'PR1–PR2 and PR4–PR5', 'region' => 'Lancashire', 'stock' => 'city housing, student lets and industrial parks', 'focus' => 'student lets, offices and warehouses'],
    'Leyland' => ['districts' => 'PR25–PR26', 'region' => 'Lancashire', 'stock' => 'town housing and industrial estates', 'focus' => 'housing and industry'],
    'Chorley' => ['districts' => 'PR6–PR7', 'region' => 'Lancashire', 'stock' => 'market-town housing and business parks', 'focus' => 'SME and residential'],
    'Bamber Bridge' => ['districts' => 'PR5', 'region' => 'Lancashire', 'stock' => 'town housing and local industry', 'focus' => 'residential and commercial'],
    'Penwortham' => ['districts' => 'PR1 south of the river', 'region' => 'Lancashire', 'stock' => 'suburban housing', 'focus' => 'residential'],
    'Fulwood' => ['districts' => 'PR2', 'region' => 'Lancashire', 'stock' => 'suburban housing and local retail', 'focus' => 'residential'],
    'Longridge' => ['districts' => 'PR3 fell side', 'region' => 'Lancashire', 'stock' => 'small-town housing and shops', 'focus' => 'residential'],
    'Garstang' => ['districts' => 'PR3 market', 'region' => 'Lancashire', 'stock' => 'market-town housing and shops', 'focus' => 'town commercial'],
    'Kirkham' => ['districts' => 'PR4 town', 'region' => 'Lancashire', 'stock' => 'market-town housing', 'focus' => 'residential'],
    'Wesham' => ['districts' => 'PR4 station', 'region' => 'Lancashire', 'stock' => 'small-town housing', 'focus' => 'residential'],
    'Lytham St Annes' => ['districts' => 'FY8', 'region' => 'Lancashire', 'stock' => 'coastal housing, hotels and retail', 'focus' => 'hospitality and residential'],
    'Blackpool' => ['districts' => 'FY1–FY4', 'region' => 'Lancashire', 'stock' => 'HMOs, guest houses, seafront retail and leisure', 'focus' => 'hospitality and multi-let housing'],
    'Fleetwood' => ['districts' => 'FY7', 'region' => 'Lancashire', 'stock' => 'coastal housing, port and retail', 'focus' => 'residential and commercial'],
    'Thornton-Cleveleys' => ['districts' => 'FY5', 'region' => 'Lancashire', 'stock' => 'coastal suburban housing and retail', 'focus' => 'residential'],
    'Poulton-le-Fylde' => ['districts' => 'FY6', 'region' => 'Lancashire', 'stock' => 'market-town housing and shops', 'focus' => 'residential'],
    'Lancaster' => ['districts' => 'LA1', 'region' => 'Lancashire', 'stock' => 'city housing, student lets and retail', 'focus' => 'student HMOs and commercial'],
    'Morecambe' => ['districts' => 'LA3–LA4', 'region' => 'Lancashire', 'stock' => 'seafront HMOs, guest houses and retail', 'focus' => 'hospitality and multi-let'],
    'Carnforth' => ['districts' => 'LA5–LA6', 'region' => 'Lancashire', 'stock' => 'small-town housing and the M6 services edge', 'focus' => 'residential and commercial'],
    'Heysham' => ['districts' => 'LA3 port', 'region' => 'Lancashire', 'stock' => 'coastal housing and port industry', 'focus' => 'residential and industrial'],
    'Barrow-in-Furness' => ['districts' => 'LA13–LA14', 'region' => 'Cumbria', 'stock' => 'town housing, shipyard industry and retail', 'focus' => 'industrial and residential'],
    'Ulverston' => ['districts' => 'LA12', 'region' => 'Cumbria', 'stock' => 'market-town housing and retail', 'focus' => 'town commercial'],
    'Dalton-in-Furness' => ['districts' => 'LA15', 'region' => 'Cumbria', 'stock' => 'small-town housing', 'focus' => 'residential'],
    'Millom' => ['districts' => 'LA18', 'region' => 'Cumbria', 'stock' => 'coastal town housing and small commercial', 'focus' => 'residential'],
    'Kendal' => ['districts' => 'LA9', 'region' => 'Cumbria', 'stock' => 'market-town retail, tourism and housing', 'focus' => 'tourism and town retail'],
    'Windermere' => ['districts' => 'LA23', 'region' => 'Cumbria', 'stock' => 'hotels, guest houses and holiday lets', 'focus' => 'hospitality'],
    'Ambleside' => ['districts' => 'LA22', 'region' => 'Cumbria', 'stock' => 'tourism accommodation and village retail', 'focus' => 'hospitality'],
    'Keswick' => ['districts' => 'CA12', 'region' => 'Cumbria', 'stock' => 'tourism accommodation and town retail', 'focus' => 'hospitality'],
    'Whitehaven' => ['districts' => 'CA28', 'region' => 'Cumbria', 'stock' => 'harbour-town housing and retail', 'focus' => 'residential and commercial'],
    'Workington' => ['districts' => 'CA14', 'region' => 'Cumbria', 'stock' => 'town housing and industrial sites', 'focus' => 'residential and industrial'],
    'Maryport' => ['districts' => 'CA15', 'region' => 'Cumbria', 'stock' => 'harbour-town housing', 'focus' => 'residential'],
    'Cockermouth' => ['districts' => 'CA13', 'region' => 'Cumbria', 'stock' => 'market-town housing and retail', 'focus' => 'town commercial'],
    'Penrith' => ['districts' => 'CA10–CA11', 'region' => 'Cumbria', 'stock' => 'market-town housing, retail and the M6 edge', 'focus' => 'town commercial'],
    'Carlisle' => ['districts' => 'CA1–CA6', 'region' => 'Cumbria', 'stock' => 'city housing, retail and logistics', 'focus' => 'commercial and multi-site'],
    'Chester' => ['districts' => 'CH1–CH4', 'region' => 'Cheshire', 'stock' => 'historic city retail, offices and suburban housing', 'focus' => 'retail and offices'],
    'Ellesmere Port' => ['districts' => 'CH65–CH66', 'region' => 'Cheshire', 'stock' => 'town housing and industrial estates', 'focus' => 'industrial and residential'],
    'Neston' => ['districts' => 'CH64', 'region' => 'Cheshire', 'stock' => 'small-town housing and shops', 'focus' => 'residential'],
    'Frodsham' => ['districts' => 'WA6 hill town', 'region' => 'Cheshire', 'stock' => 'small-town housing and shops', 'focus' => 'residential'],
    'Helsby' => ['districts' => 'WA6 station', 'region' => 'Cheshire', 'stock' => 'village housing', 'focus' => 'residential'],
    'Tarvin' => ['districts' => 'CH3', 'region' => 'Cheshire', 'stock' => 'village housing', 'focus' => 'residential'],
    'Tarporley' => ['districts' => 'CW6', 'region' => 'Cheshire', 'stock' => 'village housing and shops', 'focus' => 'residential'],
    'Nantwich' => ['districts' => 'CW5', 'region' => 'Cheshire', 'stock' => 'historic town retail and housing', 'focus' => 'town retail and residential'],
    'Crewe' => ['districts' => 'CW1–CW3', 'region' => 'Cheshire', 'stock' => 'rail-town housing, logistics and industry', 'focus' => 'industrial and multi-let'],
    'Sandbach' => ['districts' => 'CW11', 'region' => 'Cheshire', 'stock' => 'market-town housing and shops', 'focus' => 'residential and retail'],
    'Middlewich' => ['districts' => 'CW10', 'region' => 'Cheshire', 'stock' => 'town housing and industry', 'focus' => 'residential and industrial'],
    'Winsford' => ['districts' => 'CW7', 'region' => 'Cheshire', 'stock' => 'town housing and industrial estates', 'focus' => 'housing and industry'],
    'Northwich' => ['districts' => 'CW8–CW9', 'region' => 'Cheshire', 'stock' => 'town housing, retail and industry', 'focus' => 'commercial and residential'],
    'Knutsford' => ['districts' => 'WA16', 'region' => 'Cheshire', 'stock' => 'town housing and retail', 'focus' => 'residential and offices'],
    'Wilmslow' => ['districts' => 'SK9 town', 'region' => 'Cheshire', 'stock' => 'suburban housing and town retail', 'focus' => 'residential and boutique commercial'],
    'Handforth' => ['districts' => 'SK9 dean row side', 'region' => 'Cheshire', 'stock' => 'suburban housing and retail sheds', 'focus' => 'residential and retail'],
    'Poynton' => ['districts' => 'SK12', 'region' => 'Cheshire', 'stock' => 'village housing and local shops', 'focus' => 'residential'],
    'Macclesfield' => ['districts' => 'SK10–SK11', 'region' => 'Cheshire', 'stock' => 'market-town housing, mills and industrial estates', 'focus' => 'SME industrial and residential'],
    'Congleton' => ['districts' => 'CW12', 'region' => 'Cheshire', 'stock' => 'mill-town housing and industry', 'focus' => 'housing and industry'],
    'Holmes Chapel' => ['districts' => 'CW4', 'region' => 'Cheshire', 'stock' => 'village housing and local shops', 'focus' => 'residential'],
    'Alsager' => ['districts' => 'ST7', 'region' => 'Cheshire', 'stock' => 'town housing and the station edge', 'focus' => 'residential'],
    'Warrington' => ['districts' => 'WA1–WA2 and WA4–WA5', 'region' => 'Cheshire', 'stock' => 'logistics warehouses, business parks and housing', 'focus' => 'warehouses and offices'],
    'Runcorn' => ['districts' => 'WA7', 'region' => 'Cheshire', 'stock' => 'new-town housing and industrial estates', 'focus' => 'industrial and multi-let'],
    'Widnes' => ['districts' => 'WA8', 'region' => 'Cheshire', 'stock' => 'housing and riverside industry', 'focus' => 'industrial and residential'],
    'Halton' => ['districts' => 'WA7–WA8 borough sites', 'region' => 'Cheshire', 'stock' => 'housing across the two town centres', 'focus' => 'multi-site housing'],
    'Appleton' => ['districts' => 'WA4 south', 'region' => 'Cheshire', 'stock' => 'suburban housing', 'focus' => 'residential'],
    'Stockton Heath' => ['districts' => 'WA4 village', 'region' => 'Cheshire', 'stock' => 'village retail and housing', 'focus' => 'shops and residential'],
    'Lymm' => ['districts' => 'WA13', 'region' => 'Cheshire', 'stock' => 'village housing and local shops', 'focus' => 'residential'],
    'Culcheth' => ['districts' => 'WA3 village green', 'region' => 'Cheshire', 'stock' => 'village housing', 'focus' => 'residential'],
    'Risley' => ['districts' => 'WA3 employment area', 'region' => 'Cheshire', 'stock' => 'housing beside employment land', 'focus' => 'industrial and residential'],
    'Birchwood' => ['districts' => 'WA3 park', 'region' => 'Cheshire', 'stock' => 'business-park offices and housing', 'focus' => 'offices and residential'],
    'Great Sankey' => ['districts' => 'WA5 west', 'region' => 'Cheshire', 'stock' => 'suburban housing', 'focus' => 'residential'],
    'Penketh' => ['districts' => 'WA5 south', 'region' => 'Cheshire', 'stock' => 'suburban housing', 'focus' => 'residential'],
    'Blackburn' => ['districts' => 'BB1–BB2', 'region' => 'Lancashire', 'stock' => 'terraced streets, mills and retail parks', 'focus' => 'residential and industrial'],
    'Darwen' => ['districts' => 'BB3', 'region' => 'Lancashire', 'stock' => 'mill-town terraces and industry', 'focus' => 'housing and industry'],
    'Accrington' => ['districts' => 'BB5 town centre', 'region' => 'Lancashire', 'stock' => 'terraces and town retail', 'focus' => 'housing and retail'],
    'Burnley' => ['districts' => 'BB10–BB12', 'region' => 'Lancashire', 'stock' => 'stone terraces and mill-town industrial estates', 'focus' => 'landlord portfolios and factories'],
    'Nelson' => ['districts' => 'BB9', 'region' => 'Lancashire', 'stock' => 'terraces and industrial estates', 'focus' => 'housing and industry'],
    'Colne' => ['districts' => 'BB8', 'region' => 'Lancashire', 'stock' => 'hill-town terraces and retail', 'focus' => 'housing and retail'],
    'Rawtenstall' => ['districts' => 'BB4 town centre', 'region' => 'Lancashire', 'stock' => 'valley-town housing and retail', 'focus' => 'town commercial'],
    'Bacup' => ['districts' => 'OL13', 'region' => 'Lancashire', 'stock' => 'hill-town stone terraces', 'focus' => 'housing'],
    'Rossendale' => ['districts' => 'BB4 valley settlements', 'region' => 'Lancashire', 'stock' => 'mill valleys with stone housing and small industry', 'focus' => 'housing and small industrial'],
    'Clitheroe' => ['districts' => 'BB7 castle side', 'region' => 'Lancashire', 'stock' => 'market-town housing and retail', 'focus' => 'town commercial'],
    'Whalley' => ['districts' => 'BB7 village', 'region' => 'Lancashire', 'stock' => 'village housing and shops', 'focus' => 'residential'],
    'Padiham' => ['districts' => 'BB12', 'region' => 'Lancashire', 'stock' => 'small-town terraces and shops', 'focus' => 'residential'],
    'Great Harwood' => ['districts' => 'BB6', 'region' => 'Lancashire', 'stock' => 'town terraces and local shops', 'focus' => 'residential'],
    'Clayton-le-Moors' => ['districts' => 'BB5 Leeds-Liverpool canal', 'region' => 'Lancashire', 'stock' => 'town housing and local industry', 'focus' => 'residential and industrial'],
    'Ramsbottom' => ['districts' => 'BL0', 'region' => 'Greater Manchester', 'stock' => 'mill-town stone housing and retail', 'focus' => 'town retail and housing'],
];
