<?php
/**
 * Legionella / water hygiene job lane.
 * Source of truth: website/data/job-types-legionella.json
 * Regenerated by: python3 website/bin/build-legionella-job-pages.py
 *
 * POA only. No invented fees, UKAS claims, lab badges or medical opinions.
 * Existing keyword copy in keywords.json is kept when a slug already has it.
 */
declare(strict_types=1);

function legionellaJobTypesExpectedCount(): int
{
    return 130;
}

function legionellaJobTypesFile(): string
{
    return SITE_ROOT . '/data/job-types-legionella.json';
}

function legionellaJobTypesOutputDir(): string
{
    return SITE_ROOT . '/pages/keywords';
}

function legionellaJobsIndexPath(): string
{
    return '/pages/resources/legionella-jobs.php';
}

function legionellaJobsIndexUrl(): string
{
    return url(legionellaJobsIndexPath());
}

function legionellaJobTypesReset(): void
{
    legionellaJobTypesData(true);
}

/** @return array{count?:int,lane?:string,groups?:list<array<string,string>>,jobs?:list<array<string,mixed>>} */
function legionellaJobTypesData(bool $reset = false): array
{
    static $data = null;
    if ($reset) {
        $data = null;
    }
    if ($data !== null) {
        return $data;
    }
    $file = legionellaJobTypesFile();
    if (!is_file($file)) {
        return $data = [];
    }
    $decoded = json_decode((string)file_get_contents($file), true);
    return $data = (is_array($decoded) ? $decoded : []);
}

/** @return list<array<string,mixed>> */
function legionellaJobTypesJobs(): array
{
    $jobs = legionellaJobTypesData()['jobs'] ?? [];
    return is_array($jobs) ? $jobs : [];
}

/** @return list<string> */
function legionellaJobTypesSlugs(): array
{
    $out = [];
    foreach (legionellaJobTypesJobs() as $job) {
        if (!is_array($job)) {
            continue;
        }
        $slug = keywordSlug((string)($job['slug'] ?? ''));
        if ($slug !== '') {
            $out[] = $slug;
        }
    }
    return $out;
}

/** @return array<string, array<string, mixed>> */
function legionellaJobTypesBySlug(): array
{
    $out = [];
    foreach (legionellaJobTypesJobs() as $job) {
        if (!is_array($job)) {
            continue;
        }
        $slug = keywordSlug((string)($job['slug'] ?? ''));
        if ($slug !== '') {
            $out[$slug] = $job;
        }
    }
    return $out;
}

/**
 * @return list<array{key:string,label:string}>
 */
function legionellaJobGroups(): array
{
    $groups = legionellaJobTypesData()['groups'] ?? [];
    if (!is_array($groups)) {
        return [];
    }
    $out = [];
    foreach ($groups as $group) {
        if (!is_array($group)) {
            continue;
        }
        $key = (string)($group['key'] ?? '');
        $label = (string)($group['label'] ?? '');
        if ($key !== '' && $label !== '') {
            $out[] = ['key' => $key, 'label' => $label];
        }
    }
    return $out;
}

/**
 * Merge lane jobs into the keyword catalogue.
 * Fields already stored for a slug (keywords.json) win.
 *
 * @param array<string, array<string, mixed>> $keywords
 * @return array<string, array<string, mixed>>
 */
function legionellaJobsApplyOverlay(array $keywords): array
{
    foreach (legionellaJobTypesJobs() as $job) {
        if (!is_array($job)) {
            continue;
        }
        $slug = keywordSlug((string)($job['slug'] ?? ''));
        if ($slug === '') {
            continue;
        }
        $base = $keywords[$slug] ?? [];
        if (!is_array($base)) {
            $base = [];
        }
        $row = $base;
        foreach (['name', 'service', 'related', 'intro', 'body', 'meta_desc', 'seo_keywords', 'h1', 'seo_title'] as $field) {
            if (empty($row[$field]) && !empty($job[$field]) && is_string($job[$field])) {
                $row[$field] = $job[$field];
            }
        }
        if (empty($row['focus_points']) && !empty($job['focus_points']) && is_array($job['focus_points'])) {
            $row['focus_points'] = $job['focus_points'];
        }
        if (empty($row['faq']) && !empty($job['faq']) && is_array($job['faq'])) {
            $row['faq'] = $job['faq'];
        }
        if (empty($row['service'])) {
            $row['service'] = 'legionella-risk-assessment';
        }
        $row['related'] = keywordSlug((string)($row['related'] ?? $job['related'] ?? $slug));
        $row['lane'] = 'legionella';
        $keywords[$slug] = $row;
    }
    return $keywords;
}
