<?php
/**
 * Nurse-call priority: one hub, two local pages, keyword copy.
 * Care homes, hospital wards and warden call are different jobs.
 * Coverage stays North West. Manchester and Burnley are written because
 * the diary goes there. No cloned UK-wide town pages.
 */
declare(strict_types=1);

function nurseCallPhone(): string
{
    return defined('PHONE') ? (string)PHONE : '07517806082';
}

/**
 * @return array<string,array<string,mixed>>
 */
function nurseCallPriorityHubs(): array
{
    $phone = nurseCallPhone();

    return [
        'nurse-call-systems' => [
            'navLabel' => 'Nurse call',
            'pageTitle' => 'Nurse Call Systems | Care, Hospital & Warden',
            'metaDesc' => 'Nurse call for care homes, hospital wards and warden schemes. Surveyed from Stockport SK2. Call ' . $phone . '. Written quotes, no catalogue fees.',
            'metaKeywords' => 'nurse call systems, care home nurse call, hospital nurse call, warden call, HTM 08-03, Stockport, Manchester, Burnley',
            'ogImage' => '/assets/images/services/nurse-call.jpg',
            'kicker' => 'Priority hub · Nurse call',
            'crumb' => 'Nurse call systems',
            'h1' => 'Nurse call systems',
            'h1Accent' => 'care, ward, or warden',
            'lede' => 'Tell us which building it is before anyone talks about a panel. A 40-bed residential home, a live ward and a sheltered scheme with a speech unit do not share a parts list.',
            'honest' => 'HTM 08-03 is the guidance we design against. We do not issue a CQC rating and we do not print an “HTM certificate”. The quote waits for a room count, a photo of the panel and whether residents stay in the building. Phone ' . $phone . '.',
            'coverTitle' => 'Three call systems, three different faults',
            'cover' => [
                'In a care home the failure is usually a pear lead, a bathroom cord or an overdoor lamp that the night station never sees. On a ward the failure is a staff station, a crash call or a zone that was reconfigured when the bed layout changed. In sheltered housing the failure is a pendant, a speech module or a door release that the scheme manager cannot answer.',
                'Fire, emergency lighting and door security for the same operator sit on the [care homes](/pages/care-homes) page. Local write-ups: [Manchester](/pages/nurse-call-manchester) and [Burnley](/pages/nurse-call-burnley). Yard: 17 Woodlands Park Road, Offerton, SK2 5DE.',
            ],
            'work' => [
                'Room-by-room surveys: bedrooms, bathrooms, lounges, sluice, staff base',
                'Call-path tests from the device to the lamp, the panel and the handset',
                'Phased replacement in an occupied home, with cover left on the wing still in use',
                'Warden and extra-care speech, pendants and door release — specified on their own',
                'Panels we already see on sites: Courtney Thorne, Intercall, Static Systems, Aidcall, Quantec',
            ],
            'whoTitle' => 'Who books this',
            'who' => [
                ['title' => 'Care home managers', 'text' => 'A dead bedroom point found on the evening drug round, or a refurb that still has residents in the other wing.'],
                ['title' => 'Hospital estates', 'text' => 'A clinic or ward instructed directly, or via the principal contractor. We are not an NHS framework holder.'],
                ['title' => 'Scheme managers', 'text' => 'Sheltered and extra-care blocks where the resident speaks to a person, rather than lighting a lamp over a bedroom door.'],
            ],
            'steps' => [
                ['title' => 'Send the panel photo', 'text' => 'Bed count, postcode, and whether the building is a care home, a ward or a warden scheme. A blurry photo of the panel beats a brand guess.'],
                ['title' => 'We walk the call path', 'text' => 'One bedroom, one bathroom, the staff base. If the cord does not reach the lamp, the quote says so before any kit is ordered.'],
                ['title' => 'Written quote, then the visit', 'text' => 'Occupied homes are phased. Empty wings can be done in a block. You get the test notes for the file, not a sticker on the panel door.'],
            ],
            'relatedGuides' => ['care-home-fire-and-nurse-call'],
            'alsoTitle' => 'Open the page that matches the building',
            'also' => [
                ['href' => '/pages/care-homes', 'label' => 'Care homes', 'note' => 'Nurse call plus fire, lighting, access and CCTV for the same operator.'],
                ['href' => '/pages/nurse-call-manchester', 'label' => 'Nurse call in Manchester', 'note' => 'South Manchester villas, Wythenshawe homes, city conversions.'],
                ['href' => '/pages/nurse-call-burnley', 'label' => 'Nurse call in Burnley', 'note' => 'East Lancashire homes. The drive from SK2 is part of the diary.'],
                ['href' => '/pages/keywords/care-home-nurse-call', 'label' => 'Care home nurse call', 'note' => 'Bedroom points, bathroom cords, overdoor lights.'],
                ['href' => '/pages/keywords/hospital-nurse-call-system', 'label' => 'Hospital nurse call', 'note' => 'Live wards and clinics. Not a care-home parts list.'],
                ['href' => '/pages/keywords/warden-call', 'label' => 'Warden call', 'note' => 'Speech, pendants and door release in sheltered schemes.'],
                ['href' => '/pages/keywords/nurse-call-maintenance', 'label' => 'Nurse call maintenance', 'note' => 'What a visit actually tests.'],
                ['href' => '/pages/services/nurse-call', 'label' => 'Nurse call service page', 'note' => 'The trade service entry, with the same phone number.'],
            ],
            'formService' => 'Nurse call',
            'formHeading' => 'Request a nurse-call quote',
            'formIntro' => 'Name the building type first. Room count and a panel photo second. Call ' . $phone . ' if the fault is on a live wing tonight.',
            'formPlaceholder' => 'Care home, ward or warden scheme. Postcode, beds, panel brand, what failed…',
            'faqs' => [
                ['q' => 'Is a warden system the same as nurse call?', 'a' => 'No. Warden call is speech, a pendant and usually a door release for a scheme manager. Nurse call in a care home is a point, a cord and a light the carer can see from the corridor. We price them as separate scopes.'],
                ['q' => 'Do you publish a page for every UK town?', 'a' => 'Manchester and Burnley have pages because we attend them from Offerton. Any other North West address is quoted from the postcode. A national care group with one home in Burnley gets a Burnley visit, not a landing page for every English county.'],
                ['q' => 'Where do I call?', 'a' => '07517806082. The yard is 17 Woodlands Park Road, Offerton, Stockport, SK2 5DE.'],
            ],
        ],
        'nurse-call-manchester' => [
            'navLabel' => 'Nurse call Manchester',
            'pageTitle' => 'Nurse Call Manchester | Care Homes & Wards',
            'metaDesc' => 'Manchester nurse call for care homes, clinics and warden schemes, attended from Offerton SK2. Call ' . $phone . '. Quote after the panel photo.',
            'metaKeywords' => 'nurse call Manchester, care home nurse call Manchester, warden call Manchester, hospital nurse call Manchester, SK2',
            'ogImage' => '/assets/images/services/nurse-call.jpg',
            'kicker' => 'Local page · Manchester',
            'crumb' => 'Nurse call in Manchester',
            'h1' => 'Nurse call in Manchester',
            'h1Accent' => 'from the Offerton yard',
            'lede' => 'South Manchester still has converted villas used as residential homes. Wythenshawe has purpose-built units with long corridors. A city-centre clinic is a loading-bay problem before it is a call-point problem.',
            'honest' => 'There is no Manchester shopfront. Travel from SK2 is usually under 40 minutes to Didsbury, Chorlton or Withington, and longer when the job is a central block with a goods lift. Phone ' . $phone . ' and give the M postcode first.',
            'coverTitle' => 'What Manchester care buildings actually throw up',
            'cover' => [
                'Converted houses hide call cable in listed plaster and box the panel in a cupboard that used to be a pantry. Purpose-built homes in Wythenshawe and the eastern estates have long corridor runs, so a dead overdoor lamp is easy to miss from the staff base. Extra-care blocks want speech at the flat door, which is a warden scope, not a bedroom pear lead.',
                'The full specification sits on [nurse call systems](/pages/nurse-call-systems). If the same visit needs the fire panel or the stair lighting, use [care homes](/pages/care-homes). East Lancashire is a different drive: [Burnley](/pages/nurse-call-burnley).',
            ],
            'work' => [
                'Occupied villas where only one floor can be opened at a time',
                'Corridor lamp checks on long purpose-built wings',
                'Clinic and ward call points when estates instruct us directly',
                'Scheme speech and pendants in extra-care blocks around the city',
            ],
            'whoTitle' => 'Typical Manchester bookings',
            'who' => [
                ['title' => 'Single converted homes', 'text' => 'A manager with one building, a panel in a cupboard, and a bathroom cord that has been taped up.'],
                ['title' => 'Groups with two or three doors', 'text' => 'We stack Didsbury, Chorlton and Stockport on one day when the panels match. Mixed brands get separate surveys.'],
                ['title' => 'Clinics inside the ring', 'text' => 'Access is the quote. Concierge, a permit and a shutdown window change the labour more than the call point does.'],
            ],
            'steps' => [
                ['title' => 'M postcode and access', 'text' => 'Parking, a goods lift, or a resident lounge we must stay out of. Those three facts move the price more than the brand name.'],
                ['title' => 'One wing, then the rest', 'text' => 'We prove the call path on a single floor before anyone talks about a full rip-out.'],
                ['title' => 'Notes the deputy can file', 'text' => 'Which rooms failed, which cords were replaced, which lamp is still waiting on a part.'],
            ],
            'relatedGuides' => ['care-home-fire-and-nurse-call'],
            'alsoTitle' => 'Related pages',
            'also' => [
                ['href' => '/pages/nurse-call-systems', 'label' => 'Nurse call systems hub', 'note' => 'Care home, hospital and warden call, specified apart.'],
                ['href' => '/pages/care-homes', 'label' => 'Care homes', 'note' => 'The wider care landing, including fire and lighting.'],
                ['href' => '/pages/nurse-call-burnley', 'label' => 'Nurse call in Burnley', 'note' => 'A longer run from SK2. Different stock.'],
                ['href' => '/pages/keywords/warden-call', 'label' => 'Warden call', 'note' => 'For extra-care and sheltered blocks, not bedroom lamps.'],
                ['href' => '/pages/areas/manchester', 'label' => 'Manchester area hub', 'note' => 'Other trades in the city. This page is the nurse-call one.'],
            ],
            'formService' => 'Nurse call — Manchester',
            'formHeading' => 'Request a Manchester nurse-call quote',
            'formIntro' => 'M postcode, building type, and how we get in. Call ' . $phone . ' if a wing is already dark.',
            'formPlaceholder' => 'M postcode, care home or clinic or scheme, beds, access, panel photo notes…',
            'faqs' => [
                ['q' => 'Do you have an office in Manchester?', 'a' => 'No. Engineers leave Offerton, SK2. South Manchester is a normal morning. A city-centre permit is booked into the quote.'],
                ['q' => 'Will you add a page for every Manchester district?', 'a' => 'No. Send the address. Didsbury and Wythenshawe are both this page until the building itself needs a different specification.'],
            ],
        ],
        'nurse-call-burnley' => [
            'navLabel' => 'Nurse call Burnley',
            'pageTitle' => 'Nurse Call Burnley | Care & Warden Call',
            'metaDesc' => 'Burnley nurse call and warden call for East Lancashire care homes. Attended from Stockport SK2. Call ' . $phone . '. The drive is in the quote.',
            'metaKeywords' => 'nurse call Burnley, care home nurse call Burnley, warden call East Lancashire, BB10 nurse call, Padiham, Nelson',
            'ogImage' => '/assets/images/services/nurse-call.jpg',
            'kicker' => 'Local page · Burnley',
            'crumb' => 'Nurse call in Burnley',
            'h1' => 'Nurse call in Burnley',
            'h1Accent' => 'East Lancashire, timed honestly',
            'lede' => 'Burnley, Padiham and the streets toward Nelson still have smaller residential homes in former mill terraces, plus a handful of purpose-built units on the edge of town. The call kit is often older wired cord, not a new radio mesh.',
            'honest' => 'SK2 to BB10 is usually the best part of an hour and a quarter, longer in the evening. A group with homes in Burnley and Nelson is one diary block. A single dead pear lead still gets a date. It does not get a story about a Burnley depot. Phone ' . $phone . '.',
            'coverTitle' => 'What we find on East Lancashire homes',
            'cover' => [
                'Terrace conversions leave the panel on a landing and the bathroom cord on a ceiling rose that has been painted over. Staff hear the sounder and still cannot see which door. That is a lamp and labelling job, not a new radio system, until the survey says the cable is actually dead.',
                'Read the specification on [nurse call systems](/pages/nurse-call-systems). Manchester is a separate page: [nurse call in Manchester](/pages/nurse-call-manchester). Fire and lighting for the same home: [care homes](/pages/care-homes).',
            ],
            'work' => [
                'Pull-cord and pear-lead repairs on occupied terrace homes',
                'Landing panels where the room labels no longer match the bedrooms',
                'Warden speech in sheltered blocks around Burnley, Nelson and Colne',
                'A second door in Accrington, Padiham or Clitheroe on the same run when the group asks',
            ],
            'whoTitle' => 'Who this page is for',
            'who' => [
                ['title' => 'Independent homes in BB10–BB12', 'text' => 'One manager, one panel, a cord that failed over the weekend and a deputy who wants the room number in writing.'],
                ['title' => 'Small groups across East Lancs', 'text' => 'Two or three homes. We book them as a run so the travel is once, not three call-out stories.'],
                ['title' => 'Sheltered schemes', 'text' => 'Speech and pendants. If the building is a nursing wing with overdoor lamps, say so — that is the other scope.'],
            ],
            'steps' => [
                ['title' => 'Say Burnley first', 'text' => 'BB postcode, bed count, and whether Nelson or Accrington is on the same instruction. That decides the day, not the sales line.'],
                ['title' => 'Open one bedroom and one bathroom', 'text' => 'Older cord systems fail at the ceiling rose and the plug, not in the brochure.'],
                ['title' => 'Leave a room list', 'text' => 'The file needs the rooms tested, not a sentence that says the system was checked.'],
            ],
            'relatedGuides' => ['care-home-fire-and-nurse-call'],
            'alsoTitle' => 'Related pages',
            'also' => [
                ['href' => '/pages/nurse-call-systems', 'label' => 'Nurse call systems hub', 'note' => 'How care, ward and warden scopes are split.'],
                ['href' => '/pages/care-homes', 'label' => 'Care homes', 'note' => 'Fire, lighting and doors as well as the call system.'],
                ['href' => '/pages/nurse-call-manchester', 'label' => 'Nurse call in Manchester', 'note' => 'Closer to the yard. Different buildings.'],
                ['href' => '/pages/keywords/care-home-nurse-call', 'label' => 'Care home nurse call', 'note' => 'The device layout a residential home usually needs.'],
                ['href' => '/pages/areas/burnley', 'label' => 'Burnley area hub', 'note' => 'Other trades. Nurse call for the town is this page.'],
                ['href' => '/pages/areas/nelson', 'label' => 'Nelson area hub', 'note' => 'Often the second door on a Burnley day.'],
            ],
            'formService' => 'Nurse call — Burnley',
            'formHeading' => 'Request a Burnley nurse-call quote',
            'formIntro' => 'BB postcode and whether another East Lancashire home should share the day. Call ' . $phone . '.',
            'formPlaceholder' => 'Burnley or nearby town, beds, wired or radio, panel on the landing or in an office…',
            'faqs' => [
                ['q' => 'Can you be in Burnley the same morning as a Stockport fault?', 'a' => 'Only if both jobs are already on that run. Otherwise Burnley is its own day, often paired with Nelson, Colne or Accrington.'],
                ['q' => 'Do you cover the rest of the UK from this page?', 'a' => 'This page is Burnley and the East Lancashire homes we can sensibly pair with it. Other counties are a phone conversation about the address, not another copy of this layout.'],
            ],
        ],
    ];
}

/**
 * Unique keyword copy for the nurse-call priority set.
 * Replaces thin or repeated catalogue text at read time.
 *
 * @return array<string,array<string,mixed>>
 */
function nurseCallPriorityKeywordOverlay(): array
{
    $phone = nurseCallPhone();

    return [
        'nurse-call-system' => [
            'name' => 'Nurse Call System',
            'service' => 'nurse-call',
            'related' => 'care-home-nurse-call',
            'intro' => 'A nurse call system is the path from the person who needs help to the person who can walk there. The hardware is the easy part to argue about. The path is the part that fails at 2am.',
            'body' => 'We start with the building, not a catalogue code. A residential home wants a point by the bed, a cord in the bathroom and a lamp the carer can see without opening the door. A ward wants a staff station and a way to mark a crash call. A sheltered scheme wants speech. Those are three systems. Mixing the parts list is how homes end up with a pendant that never lights a corridor lamp, or a clinical panel in a block of flats. After the survey you get a written quote from the Offerton yard. Call ' . $phone . ' with the postcode and a photo of whatever is already on the wall. Manchester and Burnley each have their own page because those runs are real; other North West towns are quoted from the address.',
            'meta_desc' => 'Nurse call systems for care homes, wards and warden schemes. Survey first. Stockport SK2. Call ' . $phone . '.',
            'seo_keywords' => 'nurse call system, care home nurse call, hospital nurse call, warden call, HTM 08-03, nurse call Stockport, nurse call Manchester, nurse call Burnley',
            'focus_points' => [
                'Separate scopes for care homes, wards and sheltered schemes',
                'Call-path test: device, lamp, panel, handset',
                'Written quote after room count and a panel photo',
                'Courtney Thorne, Intercall, Static Systems, Aidcall, Quantec on existing sites',
            ],
            'faq' => [
                ['Which nurse call system should a care home buy?', 'The one that matches the building you have. Stone walls, a live wing and a panel you can still get parts for matter more than a feature list. We say which after the survey.'],
                ['Do you publish a price list?', 'No. Beds, cable and whether people stay in the rooms change the figure. You get a written quote, not a web fee.'],
                ['Where are the engineers based?', '17 Woodlands Park Road, Offerton, Stockport, SK2 5DE. Phone ' . $phone . '.'],
            ],
        ],
        'care-home-nurse-call' => [
            'name' => 'Care Home Nurse Call',
            'service' => 'nurse-call',
            'related' => 'nursing-home-nurse-call',
            'intro' => 'Care home nurse call fails in ordinary ways: a pear lead pulled out of the socket, a bathroom cord painted into the ceiling, a lamp lit on a corridor nobody walks after tea.',
            'body' => 'The layout that works in most residential homes is dull and specific. A call point the resident can reach from the pillow. A cord in the bathroom that resets in the bathroom, not from the office. An overdoor lamp on the hinge side so a carer sees it before they pass the room. A sounder at the night station that is not drowned by the television in the lounge. Wander alarms and staff-attack fobs are extra devices with their own test, not a tick on the same sheet. We phase occupied homes one wing at a time and leave the other wing calling. If the building is a nursing unit with higher dependency, that is a denser layout. If it is sheltered housing with speech, it is warden call. Phone ' . $phone . '.',
            'meta_desc' => 'Care home nurse call: bedroom points, bathroom cords, overdoor lamps. Occupied homes phased. Call ' . $phone . '.',
            'seo_keywords' => 'care home nurse call, residential care call system, pear lead, bathroom pull cord, overdoor light, nurse call Stockport',
            'focus_points' => [
                'Pillow point, bathroom cord, overdoor lamp, night station',
                'Reset in the room, not only at the office panel',
                'Occupied wings left live while the other wing is opened',
                'Wander and staff-attack tested on their own sheet',
            ],
            'faq' => [
                ['Can you work while residents are in the home?', 'Yes. One wing at a time, with the other wing still calling. A full weekend strip with no temporary cover is the wrong plan.'],
                ['What should I photograph?', 'The panel, one bedroom point, and the bathroom cord. Add the room that failed if you know it.'],
                ['Is this the same kit as a hospital ward?', 'No. A care home is points, cords and lamps. A ward has a staff station and crash call. We do not swap the schedules.'],
            ],
        ],
        'nursing-home-nurse-call' => [
            'name' => 'Nursing Home Nurse Call',
            'service' => 'nurse-call',
            'related' => 'hospital-nurse-call-system',
            'intro' => 'A nursing home is not a residential home with a different sign. More people need the cord, more rooms have an ensuite, and the priority call has to beat the routine one.',
            'body' => 'Dependency changes the count. Ensuites need their own cord. Treatment rooms and sluices need a point staff will actually use, not one behind a trolley. The display at the nurses’ station has to show which call is urgent when three sound at once. We test that order on site, with a person in the corridor, because a bench test in the panel cupboard lies. Maintenance then repeats the same paths: ensuite, bed, priority, reset. If your building is still a standard residential layout, use the care-home page. If it is a ward in a hospital, use the hospital page. Call ' . $phone . ' and say nursing home in the first sentence so the survey brings the denser checklist.',
            'meta_desc' => 'Nursing home nurse call with ensuite cords and priority calls. Denser than a residential home. Call ' . $phone . '.',
            'seo_keywords' => 'nursing home nurse call, ensuite pull cord, priority call, nurses station display, nurse call North West',
            'focus_points' => [
                'Ensuite cord as well as the bedroom point',
                'Priority call checked against two ordinary calls',
                'Sluice and treatment room points staff can reach',
                'Station display read from the corridor, not the cupboard',
            ],
            'faq' => [
                ['How is this different from residential care call?', 'More cords, a real priority level, and a station that can show which room is urgent. Residential homes often only need the lamp and the sounder.'],
                ['Do you rip out a working residential system?', 'Only when the survey shows it cannot carry the extra cords and the priority. Otherwise we extend what is there.'],
                ['Who attends?', 'Engineers from Offerton, SK2. Phone ' . $phone . '.'],
            ],
        ],
        'hospital-nurse-call-system' => [
            'name' => 'Hospital Nurse Call System',
            'service' => 'nurse-call',
            'related' => 'htm-08-03',
            'intro' => 'Hospital nurse call is a live-estate problem. The ward does not close because a call point is being swapped, and the infection-control rules for that bay are part of the job.',
            'body' => 'We attend clinics, community hospitals and wards when estates or the principal contractor instructs us. We are not on an NHS framework, and we will not invent one to win the enquiry. The useful information is the staff-station location, how crash call is raised, which bays can be isolated, and whether the existing cable can stay. HTM 08-03 is the guidance those conversations use. It is not a logo we add to the invoice. A care-home pear-lead schedule is the wrong document for this building. Send the ward name, the shutdown window and a photo of the station to ' . $phone . '.',
            'meta_desc' => 'Hospital and clinic nurse call for live wards. Not an NHS framework. Quote from Stockport. Call ' . $phone . '.',
            'seo_keywords' => 'hospital nurse call system, ward call system, crash call, HTM 08-03, clinic nurse call, healthcare estates North West',
            'focus_points' => [
                'Live bays isolated instead of a whole-ward shutdown',
                'Crash call and staff station checked as a pair',
                'Instruction from estates or the principal contractor',
                'HTM 08-03 used as guidance, not as a badge',
            ],
            'faq' => [
                ['Are you an NHS framework supplier?', 'No. We work by direct instruction or under a principal contractor. Say which at the start.'],
                ['Can a care-home system be dropped onto a ward?', 'No. Staff stations, crash call and bay isolation are a different specification.'],
                ['What do you need before a figure?', 'Ward name, how many bays can close, and a photo of the staff station. Phone ' . $phone . '.'],
            ],
        ],
        'warden-call' => [
            'name' => 'Warden Call',
            'service' => 'nurse-call',
            'related' => 'nurse-call-system',
            'intro' => 'Warden call is the system in sheltered and extra-care housing where a resident presses a pendant or a wall unit and a person answers by speech.',
            'body' => 'The scheme manager, or an off-site centre, needs to hear the flat and release the door. That is a speech module, a pendant or pull cord, and a door-release contact. It is not an overdoor lamp outside a care-home bedroom, and it is not a hospital staff station. We survey the scheme office, a sample flat, the entrance panel and the place the pendant is supposed to reach — bathroom included, because that is where people fall. Radio pendants need a walk from the flat to the lift and down to the entrance, not a tick in the lounge. If your building is a registered care home with corridor lamps, ask for care-home nurse call instead. Housing associations with two blocks in the same town can share a day. Call ' . $phone . '.',
            'meta_desc' => 'Warden call for sheltered and extra-care schemes: speech, pendants, door release. Call ' . $phone . '.',
            'seo_keywords' => 'warden call, sheltered housing call system, extra care pendant, scheme manager intercom, door release, warden call North West',
            'focus_points' => [
                'Speech between the flat and the scheme manager',
                'Pendant or cord checked in the bathroom, not only the lounge',
                'Door release tested on the same visit as the call',
                'Radio walk from the flat to the lift and the entrance',
            ],
            'faq' => [
                ['Is warden call the same product as nurse call?', 'No. Warden call is speech and a door. Care-home nurse call is a lamp in a corridor. The wiring and the test sheet differ.'],
                ['Can you take over a scheme another company monitored?', 'The on-site kit, yes, after we see the speech unit and the pendants. Off-site monitoring contracts are a separate agreement. Tell us who answers the call today.'],
                ['Which towns?', 'North West schemes from Stockport SK2, including Manchester and Burnley when that is the address. Phone ' . $phone . '.'],
            ],
        ],
        'nurse-call-maintenance' => [
            'name' => 'Nurse Call Maintenance',
            'service' => 'nurse-call',
            'related' => 'wireless-nurse-call-system',
            'intro' => 'Nurse call maintenance is a list of calls you make on purpose, then write down. A sticker on the panel door is not the record.',
            'body' => 'A useful visit picks rooms, not “the system”. Press the bedroom point. Pull the bathroom cord. Watch the overdoor lamp from the corridor. Reset in the room and confirm the panel clears. Open the power supply and read the battery date. On a radio system, note which pendants were dead rather than writing “wireless checked”. Faults found on the day get a room number. Faults that need a part get a date, not a promise that the van is full of every historic plug. Care groups with several homes get the same sheet each time so a deputy can compare April with October. Call ' . $phone . ' and say when the last test was, even if the answer is that nobody knows.',
            'meta_desc' => 'Nurse call maintenance that tests the call path and records the room. Batteries included. Call ' . $phone . '.',
            'seo_keywords' => 'nurse call maintenance, nurse call PPM, call point test, pear lead check, nurse call battery, care home service contract',
            'focus_points' => [
                'Named rooms tested, not a single “system OK” line',
                'Bathroom cord, bedroom point, lamp, reset, panel clear',
                'Battery date read on the power supply',
                'The same sheet on the next visit so the file can be compared',
            ],
            'faq' => [
                ['How often should the system be visited?', 'Follow the manufacturer’s interval and your own policy. Many homes pair a staff check each week with an engineer visit on a longer cycle. We agree the cycle from the panel you have.'],
                ['Will you maintain a system you did not install?', 'Yes, after the first visit maps the panel and the device types. Unknown plugs are quoted when we see them.'],
                ['What if a point fails between visits?', 'Call ' . $phone . ' with the room number. A dark wing is booked ahead of a paperwork tidy-up.'],
            ],
        ],
        'wireless-nurse-call-system' => [
            'name' => 'Wireless Nurse Call System',
            'service' => 'nurse-call',
            'related' => 'warden-call',
            'intro' => 'Wireless nurse call earns its place when the building cannot take new cable without closing bedrooms. It loses its place when nobody has walked the radio path.',
            'body' => 'Stone party walls, foil-backed plasterboard and a lift shaft will swallow a signal that looked fine in the lounge. We walk a pendant or a call point from the pillow to the bathroom, then to the far end of the corridor, and we write down the rooms that need a repeater. Batteries are a maintenance item with dates, not a surprise in month fourteen. A hybrid is often the honest answer: leave the wired panel, put radio only in the rooms you cannot rewire. If the home is empty for a refurbishment, cable is usually the calmer twenty-year choice. We will say that on the survey rather than sell a mesh you do not need. Call ' . $phone . ' and mention the wall construction if you know it.',
            'meta_desc' => 'Wireless nurse call only after a radio walk-test. Stone walls and batteries change the quote. Call ' . $phone . '.',
            'seo_keywords' => 'wireless nurse call system, radio nurse call, nurse call repeater, wireless care home call, hybrid nurse call',
            'focus_points' => [
                'Walk-test from pillow to bathroom to the far corridor',
                'Repeaters noted per room, not “coverage OK”',
                'Battery dates on the maintenance sheet',
                'Hybrid when the panel is sound and only some rooms are blocked',
            ],
            'faq' => [
                ['Is wireless always quicker in an occupied home?', 'It avoids chasing cable through live bedrooms. It is slower if the survey finds three dead spots and the repeaters were never in the budget.'],
                ['When is cable the better choice?', 'An empty refurbishment, or a building where the old wiring still carries a call. We say which after we test, not from the enquiry form.'],
                ['Does this include warden pendants?', 'A pendant in a sheltered flat is warden call. Say which building you have when you ring ' . $phone . '.'],
            ],
        ],
        'htm-08-03' => [
            'name' => 'HTM 08-03',
            'service' => 'nurse-call',
            'related' => 'nurse-call-maintenance',
            'intro' => 'HTM 08-03 is NHS guidance for emergency call systems in healthcare buildings. People ask us to “make it HTM” as if that were a stamp. It is a document you design against.',
            'body' => 'The parts that change a real scheme are call devices people can reach, indication staff can see, a reset that cannot be faked from the office, power that survives a mains failure for the period the guidance expects, and a maintenance record that names the rooms. We use those points on hospitals, clinics and on care homes where the operator has chosen the memo as their benchmark. A private care home is not automatically inside the memo. If you want it as the benchmark, say so, and the survey will mark gaps against those points rather than against a slogan. We do not sell an HTM certificate. The output is a device list, a test sheet and a quote. Call ' . $phone . ' if an estates paper has already named the memo and you need the gaps in writing.',
            'meta_desc' => 'HTM 08-03 used as guidance for call systems, not sold as a certificate. Gaps written down. Call ' . $phone . '.',
            'seo_keywords' => 'HTM 08-03, emergency call systems guidance, healthcare nurse call, HTM nurse call survey, call system resilience',
            'focus_points' => [
                'Reach, indication, reset, standby power, named-room records',
                'Gap list against the memo when you ask for that benchmark',
                'No HTM certificate and no CQC rating from us',
                'Care homes only use the memo when you set it as the benchmark',
            ],
            'faq' => [
                ['Does HTM 08-03 apply to every care home?', 'It is healthcare guidance. Some care operators adopt it as their benchmark. We follow it when you ask us to, and we say when a residential layout is being judged by a ward document.'],
                ['Can you upgrade only the gaps?', 'Yes. A missing bathroom reset or a dead standby battery does not always mean a new panel.'],
                ['What do we receive?', 'A written gap list and, if you proceed, test notes. Not a certificate with HTM on the letterhead. Phone ' . $phone . '.'],
            ],
        ],
        'ascom-nurse-call' => [
            'name' => 'Ascom Nurse Call',
            'service' => 'nurse-call',
            'related' => 'hospital-nurse-call-system',
            'intro' => 'Ascom nurse call usually means a staff handset and a messaging path, not only a lamp over a bedroom door. The handset is useless if the bay address in the system is wrong.',
            'body' => 'On a survey we ask which handsets the night shift actually carries, which rooms are missing from the address book, and whether a dead charger has been sitting in the office since the last audit. We test one call from a bay to a handset in a corridor, then the reset. Care homes that only need overdoor lamps are often on a different brand. If the panel photo is not Ascom, say so before anyone orders a handset. Written quote from Offerton. Call ' . $phone . '.',
            'meta_desc' => 'Ascom nurse call: handsets, bay addresses and a live call test. Quote after a panel photo. Call ' . $phone . '.',
            'seo_keywords' => 'Ascom nurse call, Ascom handset, ward messaging, nurse call handset repair, Ascom Stockport',
            'focus_points' => [
                'Handset charging and bay address checked together',
                'One live call from a bay to a handset in the corridor',
                'Reset confirmed before the visit is called finished',
                'Wrong-brand panels sent back to the correct scope',
            ],
            'faq' => [
                ['Do you only attend hospitals for Ascom?', 'No. Some care buildings use handsets too. The test is the same: the call has to arrive on the device staff carry.'],
                ['Can you add one handset?', 'Often, after we see the system generation. A photo of the charger base and the panel screen saves a wasted visit.'],
                ['Where do you work from?', 'Offerton, SK2. Phone ' . $phone . '.'],
            ],
        ],
        'emergency-assistance-alarm' => [
            'name' => 'Emergency Assistance Alarm',
            'service' => 'nurse-call',
            'related' => 'care-home-nurse-call',
            'intro' => 'An emergency assistance alarm in a WC is the red cord and the lamp outside the door. It is there so someone on the floor can get help without a bedroom panel being involved.',
            'body' => 'The cord has to hang where a person on the floor can reach it, the reset has to be inside the room, and the lamp has to be visible from the approach, not hidden behind the door swing. We see these on care-home ensuites, clinic toilets and accessible WCs in extra-care schemes. They are a small scope. They still fail when the cord is knotted up to the ceiling rose to stop “false calls”. We put the cord back at the right length and test the lamp. If the building’s main nurse call is dead as well, that is a separate quote. Call ' . $phone . ' and name the room.',
            'meta_desc' => 'Emergency assistance alarms: WC cords, in-room reset, lamp outside the door. Call ' . $phone . ' with the room.',
            'seo_keywords' => 'emergency assistance alarm, disabled WC alarm, bathroom pull cord, assistance alarm reset, care home WC alarm',
            'focus_points' => [
                'Cord length checked from the floor, not the ceiling',
                'Reset inside the room',
                'Lamp visible on the approach to the door',
                'Separate quote if the whole nurse-call panel is dead',
            ],
            'faq' => [
                ['Is this the same as a bedroom nurse call point?', 'No. This is the WC alarm: cord, reset, lamp. The bedroom point is a different device on the care-home system.'],
                ['Why do staff tie the cord up?', 'False calls. The cord then fails the person who has fallen. We refit it and agree a reset habit instead.'],
                ['How do I book?', 'Phone ' . $phone . ' with the building and the room name.'],
            ],
        ],
        'emergency-pull-cord-system' => [
            'name' => 'Emergency Pull Cord System',
            'service' => 'nurse-call',
            'related' => 'care-home-nurse-call',
            'intro' => 'A pull-cord system is the old care-home pattern: a cord in the room, a buzzer, sometimes a lamp. It still works when the cord, the ceiling rose and the fuse are the parts you actually test.',
            'body' => 'Terrace homes in East Lancashire and converted houses around Manchester often still have this. The fault is frequently the rose, a painted cord or a plug behind the bed, not the “need for a radio upgrade”. We open one room, pull the cord, and follow the sound. If several rooms are dead on the same floor, then we look at the landing fuse and the cable, and we say whether a radio overlay is worth it. An empty refurbishment can take new cable. An occupied home with three working floors should not be sold a full replacement off a phone call. Call ' . $phone . '.',
            'meta_desc' => 'Emergency pull cords tested at the rose, the cord and the sounder. Upgrade only if the cable is dead. Call ' . $phone . '.',
            'seo_keywords' => 'emergency pull cord system, care home pull cord, ceiling rose nurse call, bathroom cord repair, pull cord Burnley',
            'focus_points' => [
                'One room pulled and followed to the sounder',
                'Ceiling rose and painted cords opened, not assumed',
                'Landing fuse checked when a whole floor is quiet',
                'Radio suggested only after the old cable fails the test',
            ],
            'faq' => [
                ['Should every pull-cord home be replaced?', 'No. If the cord rings the right lamp, repair the cord. Replacement is for dead cable or a layout that cannot show which room called.'],
                ['Do you cover Burnley terrace homes?', 'Yes. BB10–BB12 is a planned run from Stockport, often paired with another East Lancashire door. See the Burnley page.'],
                ['What do you need from me?', 'The room that failed, and whether the sounder still clicks. Phone ' . $phone . '.'],
            ],
        ],
        'hospital-nurse-call-upgrade' => [
            'name' => 'Hospital Nurse Call Upgrade',
            'service' => 'nurse-call',
            'related' => 'hospital-nurse-call-system',
            'intro' => 'A hospital nurse call upgrade is a phased swap on a live ward. The question is which bays can close, not which brochure has the most icons.',
            'body' => 'We keep the staff station answering while one bay is changed, then we test crash call before the bay reopens. Cable that still carries a call stays. Cable that does not is replaced in that bay only. Estates or the principal contractor has to own the shutdown window and the infection-control rules. We are not an NHS framework supplier. A care-home upgrade plan — wings and pear leads — is the wrong programme for this building. Send the ward name and how many bays can be empty on a given day. Call ' . $phone . '.',
            'meta_desc' => 'Hospital nurse call upgrades phased by bay on a live ward. Not an NHS framework. Call ' . $phone . '.',
            'seo_keywords' => 'hospital nurse call upgrade, ward call upgrade, live ward nurse call, crash call test, healthcare estates',
            'focus_points' => [
                'One bay closed, the rest of the ward still calling',
                'Crash call tested before the bay reopens',
                'Sound cable kept, dead cable replaced in that bay',
                'Shutdown window agreed with estates first',
            ],
            'faq' => [
                ['Can you upgrade a whole hospital in a weekend?', 'Not as a serious plan. Bays reopen only after that bay’s call path is tested.'],
                ['Who instructs the work?', 'Estates or the principal contractor. Say which when you call ' . $phone . '.'],
                ['Do you publish a per-bed price?', 'No. Bay access and whether the cable can stay decide the quote.'],
            ],
        ],
        'nurse-call-certification' => [
            'name' => 'Nurse Call Certification',
            'service' => 'nurse-call',
            'related' => 'htm-08-03',
            'intro' => 'People ask for a nurse call certificate. What the file can honestly hold is a test sheet: rooms pressed, lamps seen, reset proved, battery date written down.',
            'body' => 'We do not issue a CQC certificate and we do not put “HTM certified” on a letterhead. HTM 08-03 is guidance. If you want the test sheet marked against those points, ask, and the gaps are listed in words. The sheet names rooms. A line that says the system passed is not a sheet. New installs get the same notes on the day of commissioning. Inherited systems get them on the first maintenance visit, after we have seen the panel. Call ' . $phone . ' and say if this is a commissioning visit or a maintenance sheet.',
            'meta_desc' => 'Nurse call records are room-by-room test sheets, not a CQC or HTM certificate. Call ' . $phone . '.',
            'seo_keywords' => 'nurse call certification, nurse call test sheet, nurse call commissioning notes, HTM 08-03 records, care home call log',
            'focus_points' => [
                'Named rooms, lamps, resets and battery dates',
                'Commissioning notes on the day a new system is handed over',
                'Gap list when you ask for an HTM 08-03 comparison',
                'No CQC rating and no HTM certificate from us',
            ],
            'faq' => [
                ['Will this satisfy an inspector?', 'Inspectors read what was tested. We supply that record. The inspection itself is not ours.'],
                ['Can you backdate a sheet?', 'No. The date is the day we pressed the points.'],
                ['How do I ask for it?', 'Phone ' . $phone . '. Say commissioning or maintenance, and how many beds.'],
            ],
        ],
        'nurse-call-maintenance-contract' => [
            'name' => 'Nurse Call Maintenance Contract',
            'service' => 'nurse-call',
            'related' => 'nurse-call-maintenance',
            'intro' => 'A nurse call maintenance contract is a diary and a sheet, repeated. It is not a discount sticker.',
            'body' => 'The contract says how many visits, which homes, and what “tested” means: bedroom point, bathroom cord, lamp, reset, battery date, room number if it failed. Reactive calls between visits are for rooms that have gone quiet, booked ahead of admin. A group with homes in Manchester and Burnley gets those addresses on the schedule as separate runs, because the drive is not the same morning. We price it after the first survey of each panel. There is no web tariff. Call ' . $phone . ' with the list of homes and the last time anyone opened the panel.',
            'meta_desc' => 'Nurse call maintenance contracts: named visits, named rooms, separate runs for Manchester and Burnley. Call ' . $phone . '.',
            'seo_keywords' => 'nurse call maintenance contract, care home PPM contract, nurse call service agreement, multi site nurse call',
            'focus_points' => [
                'Visit count and home list written in the contract',
                'The same room-level test each visit',
                'Manchester and Burnley booked as different runs',
                'Price after each panel has been seen once',
            ],
            'faq' => [
                ['Do you publish contract prices?', 'No. Panel type and how many homes share a day change it.'],
                ['Can one contract cover fire alarms too?', 'Fire is a different visit and a different sheet. The care homes page is where those scopes sit together.'],
                ['How do we start?', 'A list of addresses and panel photos. Phone ' . $phone . '.'],
            ],
        ],
        'nurse-call-near-me' => [
            'name' => 'Nurse Call Near Me',
            'service' => 'nurse-call',
            'related' => 'nurse-call-system',
            'intro' => '“Near me” for nurse call means the engineer leaves Offerton, SK2, with the right panel notes. It does not mean a cloned page for your street.',
            'body' => 'South Manchester is often a normal morning from the yard. Burnley, Nelson and Accrington are a planned East Lancashire day, usually the best part of an hour and a quarter. If your home is in one of those two areas, use the Manchester or Burnley page. Anywhere else in the North West, send the postcode. We will say whether it fits a day we are already running, or needs its own visit. We do not keep a depot in every town, and we do not pretend a national care group’s head office is our patch. The building is the patch. Call ' . $phone . ' and say the town in the first sentence.',
            'meta_desc' => 'Nurse call from Stockport SK2. Manchester and Burnley have pages. Other North West towns: send the postcode. ' . $phone . '.',
            'seo_keywords' => 'nurse call near me, nurse call Stockport, nurse call Manchester, nurse call Burnley, local nurse call engineer',
            'focus_points' => [
                'Yard at 17 Woodlands Park Road, Offerton, SK2 5DE',
                'Manchester page for city care buildings',
                'Burnley page for East Lancashire runs',
                'Other North West postcodes quoted from the address',
            ],
            'faq' => [
                ['Do you cover my town?', 'If it is in the North West, phone ' . $phone . ' with the postcode. Manchester and Burnley are already written up. Other towns are booked from the address.'],
                ['Will you write a page for my village?', 'No. The certificate and the test sheet do not need a unique URL. The visit needs the address.'],
                ['How fast can you reach Burnley?', 'It is a planned run, not a twenty-minute call-out from a local depot we do not have.'],
            ],
        ],
        'nurse-call-servicing' => [
            'name' => 'Nurse Call Servicing',
            'service' => 'nurse-call',
            'related' => 'nurse-call-maintenance',
            'intro' => 'Servicing a nurse call system means making calls on purpose while the home is awake enough for staff to walk to the lamp with you.',
            'body' => 'We agree a floor and a start time with the manager so medication rounds are not the moment we pull every cord. Each room on that floor is pressed, watched and reset. Rooms we could not enter are listed as not tested, which is more useful than a pass mark. Batteries and pendant dates are read if the system is radio. The notes go to the person who files the care record, not only to the inbox that booked us. For the contract version of this, see maintenance. For a dead room tonight, phone ' . $phone . ' with the room number.',
            'meta_desc' => 'Nurse call servicing by floor: pressed, watched, reset, or marked not tested. Call ' . $phone . '.',
            'seo_keywords' => 'nurse call servicing, nurse call service visit, care home call test, nurse call logbook, nurse call engineer',
            'focus_points' => [
                'Floor and start time agreed around the drug round',
                'Rooms not entered are marked not tested',
                'Radio pendants get a date, not a shrug',
                'Notes sent to the person who keeps the care file',
            ],
            'faq' => [
                ['Is servicing the same as a repair?', 'Servicing is the planned test. A repair is the room that failed. We can do the repair on the same day if the part is a common lead or cord.'],
                ['Do you need staff with you?', 'Someone who can open bedrooms and stand at the lamp. We do not test occupied rooms alone.'],
                ['What is the number?', $phone . '. Say which floor is free.'],
            ],
        ],
        'nursing-home-call-system' => [
            'name' => 'Nursing Home Call System',
            'service' => 'nurse-call',
            'related' => 'nursing-home-nurse-call',
            'intro' => 'A nursing home call system has to show which of three simultaneous calls is the one that cannot wait. A single buzzer for the whole floor hides that.',
            'body' => 'We count ensuites as well as beds. A cord in the ensuite that shares a lamp with the bedroom is acceptable only if staff can tell the calls apart. If they cannot, the quote says so. The station display is read from where the nurse actually stands, which is often the clinical room door, not the chair in front of the panel. Priority is tested by making a normal call and an urgent call together. This is denser than a residential home and quieter than a hospital bay programme. If you are unsure which you run, say how many nurses are on at night. Call ' . $phone . '.',
            'meta_desc' => 'Nursing home call systems with ensuite cords and a priority the station can see. Call ' . $phone . '.',
            'seo_keywords' => 'nursing home call system, ensuite nurse call, priority nurse call, nursing station display, nurse call North West',
            'focus_points' => [
                'Ensuite counted separately from the bed',
                'Two calls at once to prove priority',
                'Display read from the doorway staff actually use',
                'Night staffing used to judge density',
            ],
            'faq' => [
                ['Is this the residential care page?', 'No. Residential layouts are on the care-home nurse call guide. This one is for nursing units.'],
                ['Can you add priority to an old panel?', 'Sometimes. If the panel cannot tell two calls apart, the survey will say replacement of the display, not of every cord.'],
                ['Who do I call?', $phone . '. Say nursing home and the night staff count.'],
            ],
        ],
        'over-door-light-nurse-call' => [
            'name' => 'Over Door Light Nurse Call',
            'service' => 'nurse-call',
            'related' => 'care-home-nurse-call',
            'intro' => 'The overdoor light is how a carer knows which room called without opening every door. If the lamp is on the hinge side, behind a hoist, or dead, the sounder is just noise.',
            'body' => 'We stand in the corridor and make the call. If we cannot see the lamp before we reach the door, the position is wrong even when the bulb works. Dead lamps are often the lamp, sometimes the fuse for that room, sometimes a label that still shows last year’s room number. We replace the lamp and correct the label on the same visit when the part is ordinary. A whole-floor lamp failure is a cable or power fault and gets a different quote. Warden schemes usually do not use corridor lamps. If your building is sheltered housing, say so. Call ' . $phone . '.',
            'meta_desc' => 'Overdoor nurse call lights checked from the corridor, not from inside the room. Call ' . $phone . '.',
            'seo_keywords' => 'overdoor light nurse call, nurse call corridor lamp, over door indicator, care home call light',
            'focus_points' => [
                'Lamp seen from the corridor approach',
                'Room label matched to the current bedroom',
                'Single dead lamp replaced apart from a floor-wide fault',
                'Warden schemes flagged when they do not use corridor lamps',
            ],
            'faq' => [
                ['The buzzer works but staff miss calls. Is that the lamp?', 'Often. We test from the corridor. A working sounder with a hidden lamp still fails the night shift.'],
                ['Can you change one lamp?', 'Yes, when the rest of that room’s call path is sound.'],
                ['How do I report it?', 'Room number and whether the sounder still rings. Phone ' . $phone . '.'],
            ],
        ],
        'staff-attack-alarm-system' => [
            'name' => 'Staff Attack Alarm System',
            'service' => 'nurse-call',
            'related' => 'care-home-nurse-call',
            'intro' => 'A staff attack alarm is the device a carer presses when they need another member of staff in that room now. It is not the resident’s pear lead.',
            'body' => 'The test is specific. Press the fob or the ceiling pull in an agreed room. The panel or handset must show a different indication from an ordinary resident call, and someone must be able to say which room without asking the person who pressed it. We do this with two staff, not alone. Batteries on radio fobs are dated. If the building has no second person on shift, the device cannot do what the policy claims, and we will write that down rather than sell another fob. Call ' . $phone . ' and say how many staff are on nights.',
            'meta_desc' => 'Staff attack alarms tested as a different indication from a resident call. Call ' . $phone . '.',
            'seo_keywords' => 'staff attack alarm, care home staff alarm, nurse call staff attack, staff fob alarm, lone worker care',
            'focus_points' => [
                'Indication different from a resident pear-lead call',
                'Room identified without asking the person who pressed it',
                'Two staff present for the test',
                'Fob battery dates written down',
            ],
            'faq' => [
                ['Is a pear lead a staff attack alarm?', 'No. The resident lead calls for care. The staff device calls for help for the carer. They need different indications.'],
                ['What if only one person is on duty?', 'The device cannot fetch a second person who is not in the building. We record that limit.'],
                ['How do we book a test?', 'Phone ' . $phone . '. Have two staff available for the rooms we agree.'],
            ],
        ],
        'staff-attack-system' => [
            'name' => 'Staff Attack System',
            'service' => 'nurse-call',
            'related' => 'staff-attack-alarm-system',
            'intro' => 'Staff attack systems on care sites are usually a fob, a ceiling pull in the lounge, or both, tied into the same panel as the resident calls.',
            'body' => 'The mistake is to test them as if they were another bedroom point. We generate a resident call and a staff call together and check the display can tell them apart. Ceiling pulls in lounges get caught by hoists and curtains. We look at that before we blame the receiver. If your policy names a radio fob and the fobs are in a drawer, the visit starts by putting them on the people who are supposed to wear them, then walking to the far bedroom. This sits beside care-home nurse call. It is not a substitute for it. Call ' . $phone . '.',
            'meta_desc' => 'Staff attack systems checked against a resident call at the same time. Fobs walked to the far room. Call ' . $phone . '.',
            'seo_keywords' => 'staff attack system, care staff alarm fob, ceiling pull staff attack, nurse call staff safety',
            'focus_points' => [
                'Resident call and staff call shown apart on one display',
                'Lounge ceiling pulls checked for hoists and curtains',
                'Fobs taken out of the drawer and walked to a far bedroom',
                'Not sold as a replacement for the resident call system',
            ],
            'faq' => [
                ['Do fobs need their own survey?', 'Yes if the building is stone or foil-lined. A fob that works in the office can die in the end bedroom.'],
                ['Can this share the nurse call panel?', 'Often. The condition is a separate indication. If the panel cannot do that, we say so.'],
                ['What is the phone number?', $phone . '.'],
            ],
        ],
        'wander-alert-system' => [
            'name' => 'Wander Alert System',
            'service' => 'nurse-call',
            'related' => 'care-home-nurse-call',
            'intro' => 'A wander alert tells staff a particular resident has gone through a particular door. It is not a lock, and it is not the bedroom call point.',
            'body' => 'We test with the door, the tag or floor mat, and a person at the station. The alert has to name the door. A beep with no location is how people reach the wrong corridor. Exit doors on care homes in Manchester villas are often the front door plus a garden door that was added later and never put on the system. We list the doors that alarm and the doors that do not. If the home wants a locked door, that is an access-control conversation with the fire release kept in mind, and it is quoted separately. Call ' . $phone . ' and say which door has been the problem.',
            'meta_desc' => 'Wander alerts that name the door, tested with the tag and a person at the station. Call ' . $phone . '.',
            'seo_keywords' => 'wander alert system, dementia door alarm, care home wander, door exit alert, nurse call wander',
            'focus_points' => [
                'Alert names the door, not only a beep',
                'Front door and later garden doors both listed',
                'Tag or mat tested with someone at the station',
                'Locks and fire release quoted as access control, separately',
            ],
            'faq' => [
                ['Will this stop a resident leaving?', 'It tells staff the door opened. A lock is a different job and has to release on the fire alarm.'],
                ['Can it share the nurse call panel?', 'On some systems, yes, as a separate event. We confirm from the panel photo before we promise it.'],
                ['How do I start?', 'Name the door. Phone ' . $phone . '.'],
            ],
        ],
        'wireless-nurse-call' => [
            'name' => 'Wireless Nurse Call',
            'service' => 'nurse-call',
            'related' => 'wireless-nurse-call-system',
            'intro' => 'Wireless nurse call is a radio point in a room that cannot take a new cable while someone is sleeping in it. The survey is a walk, not a tick box.',
            'body' => 'We carry a point from the pillow to the bathroom and down the corridor and we write the room if the lamp or handset misses it. Repeaters are then a line on the quote, not a surprise. Batteries get dates on the service sheet. If the home is empty and the floors are up, we will usually say cable instead. A pendant in a sheltered flat is warden call, which is speech and a door, and it has its own page. Call ' . $phone . ' and describe the walls if you know them: stone, foil board, or ordinary stud.',
            'meta_desc' => 'Wireless nurse call quoted after a room-to-room radio walk. Cable recommended when the home is empty. Call ' . $phone . '.',
            'seo_keywords' => 'wireless nurse call, radio nurse call care home, wireless call point, nurse call repeater, hybrid nurse call',
            'focus_points' => [
                'Walk from pillow to bathroom to corridor, room noted if it misses',
                'Repeaters priced on the quote when the walk fails',
                'Cable preferred when the building is empty and floors are up',
                'Sheltered pendants redirected to warden call',
            ],
            'faq' => [
                ['Is wireless cheaper?', 'It can be, until repeaters and battery visits are on the sheet. The walk tells you which.'],
                ['What is the longer guide?', 'Wireless nurse call system, linked from this page. Same yard, more of the radio detail.'],
                ['Phone?', $phone . '. Offerton, SK2.'],
            ],
        ],
    ];
}
