<?php
/**
 * Bespoke articles for sitemap town pages.
 *
 * A service×town URL is indexable only when every Tier-1 town has an entry
 * here. The wording is written for that pair. Do not swap the town name into
 * a shared paragraph — check-town-uniqueness.php rejects repeated 6-word runs.
 */
declare(strict_types=1);

/**
 * @return array{services: array<string, array<string, string>>}
 */
function icomplyTier1CopyMap(): array
{
    static $map = null;
    if ($map !== null) {
        return $map;
    }
    $map = [
        'services' => [
            'electrical' => icomplyTier1ElectricalArticles(),
            'gas-systems' => icomplyTier1GasArticles(),
            'fire-alarms' => icomplyTier1FireArticles(),
            'emergency-lighting' => icomplyTier1LightingArticles(),
        ],
    ];
    return $map;
}

function icomplyTier1ResolveArea(string $areaOrSlug): string
{
    $areaOrSlug = trim($areaOrSlug);
    if ($areaOrSlug === '') {
        return '';
    }
    if (function_exists('areaFromSlug') && function_exists('areaSlug')) {
        $found = areaFromSlug(areaSlug($areaOrSlug));
        if (is_string($found) && $found !== '') {
            return $found;
        }
    }
    return $areaOrSlug;
}

function icomplyTier1ServiceArticle(string $serviceSlug, string $areaOrSlug): string
{
    if (!function_exists('areaSlug') || !function_exists('icomplyTier1Towns')) {
        return '';
    }
    $serviceSlug = areaSlug($serviceSlug);
    $map = icomplyTier1CopyMap();
    $towns = $map['services'][$serviceSlug] ?? null;
    if (!is_array($towns)) {
        return '';
    }
    foreach (icomplyTier1Towns() as $town) {
        if (trim((string)($towns[$town] ?? '')) === '') {
            return '';
        }
    }
    $name = icomplyTier1ResolveArea($areaOrSlug);
    return trim((string)($towns[$name] ?? ''));
}

/** @return array<string, string> */
function icomplyTier1ElectricalArticles(): array
{
    return [
        'Stockport' => 'Edgeley terraces, flats over Hillgate shops and the small industrial sheds off the A6 are the Stockport jobs that usually need an electrical inspection. SK1 to SK8 also takes in the town-centre retail units and the houses out through Cheadle Hulme, Bramhall and Hazel Grove. Because the office is in SK2, a morning in Marple or Romiley is a short run, not an overnight diary block. What gets opened is normally a rented house board, a flat above a shop, or a unit where the tenant has added sockets. The engineer counts circuits, looks at whether the loft is boarded, and notes if anyone is still living there. Insurer letters from local agents tend to ask for the observation codes, not a trade-body logo. Poynton houses on the edge of that patch are booked the same way once the access note arrives.',
        'Manchester' => 'Manchester electrical visits split between Victorian terraces, city-centre apartments and multi-let offices rather than one housing type. Districts M1 to M40 cover that spread, from Deansgate blocks to older streets in Chorlton and Didsbury. A high-rise riser is a different appointment from a two-storey house in Salford-facing streets: the caretaker, the lift and the landlord’s meter cupboard all have to be named before anyone travels. Boards in converted mills are often buried behind shop fit-outs. The report lists circuit protection as found, including old rewireable fuses where they are still in use. Trafford and Tameside addresses are not folded into a Manchester booking; they have their own pages. Manchester City Council governs that city. This firm is a separate business and does not hold a council contract.',
        'Salford' => 'Salford electrical work clusters around MediaCity offices, newer apartments at M50 and the older terraces towards Eccles, Swinton and Walkden. Diary postcodes include M50 at the quays, M3 nearer the centre, and M5, M6 or M7 further out. A quayside office floor needs a different test plan from a house in Worsley: raised floors, comms rooms and a facilities manager who wants the shutdown window in writing. Irlam and Trafford-side units are only added when the instruction actually names them. The visit records what protection is fitted and which circuits could not be isolated because a tenant refused access. Salford City Council runs the city. Nothing on this page is a statement from that council, and no framework agreement is claimed.',
        'Trafford' => 'Trafford’s electrical diary jumps between Altrincham offices, Sale semis, Stretford blocks and Urmston parades. Old Trafford mail is M16 or M17, Stretford is M32, Sale is M33, Urmston is M41, and Altrincham uses WA14 or WA15. A Sale shop with rooms upstairs is not tested like a business-park unit: the shop shutters, the flat’s separate board and the shared stair lighting all need their own lines on the sheet. Chorlton is close but it is not automatically part of a Trafford booking. Boards in older Altrincham houses are often still in the under-stairs cupboard behind stored paint. The engineer photographs the label, not a stock image. Trafford Council governs the borough. This company does not speak for it and does not claim a civic contract.',
        'Tameside' => 'Tameside electrical instructions usually name a terrace in Ashton-under-Lyne, a shop in Hyde, or an industrial bay in Denton, Dukinfield or Stalybridge. Ashton uses OL5, OL6 and OL7; Hyde, Denton and Stalybridge use SK14, SK15 and SK16. Mossley and Droylsden appear when the landlord’s portfolio crosses the boundary, not as filler. Many boards sit in a communal cupboard that also holds the water stopcock, so the test waits until the agent has warned every flat. Mill conversions hide sub-mains behind new plasterboard. The notes say which floors were energised and which cupboard was locked. Tameside Metropolitan Borough Council is the name on the civic website. iComply is not that council and is not on a council framework.',
        'Oldham' => 'Oldham electrical appointments are mostly terraced streets, small warehouses and the town-centre units around OL1 to OL9. Failsworth yards, Lees hills, Shaw centres, Royton shops and Chadderton side streets each bring a different access problem: a ginnel, a yard shutter, or a first-floor flat reached from a shop. Rochdale is the neighbouring borough and is not billed as Oldham. Older boards in these streets are frequently still ceramic fuses, so the sheet records that instead of assuming a modern consumer unit. Warehouse units on the edge of town often have a three-phase supply for racking that the letting brochure never mentions. The visit confirms the supply before any remedial list is written. Oldham Council governs the borough. This page does not claim to represent it.',
        'Bolton' => 'Bolton electrical jobs land on terraces, converted mills and the retail parks around BL1 to BL7. Horwich, Farnworth and Westhoughton are separate bookings from the town centre because the keys and the parking are not the same. A mill floor split into studios can have one intake and four sub-boards added by different fit-out contractors. The test follows each board back to that intake rather than sampling one studio and guessing. Bury and Wigan border the borough; they are not appended to a Bolton address to thicken the page. Radcliffe instructions are accepted only when the postcode is actually Radcliffe. Bolton Council governs the borough. No council accreditation is stated here.',
        'Wigan' => 'Wigan electrical cover follows the housing estates and the industrial corridors on WN1 to WN6, plus a Leigh house, a Hindley terrace, a Standish estate or a Golborne unit when the instruction uses those names, and the Makerfield address only when the order writes it out in full. A former pit village terrace is a different board from a newer estate house in Standish: the earth arrangements and the outbuilding supplies rarely match. Atherton and the Bolton boundary are easy to muddle on a portfolio spreadsheet, so the sheet uses the postcode the agent sent, not the nearest famous town. Multi-site landlords often want several houses on one day; that only works when every tenant has agreed a slot. Wigan Council governs the borough. This firm is not a council contractor.',
        'Liverpool' => 'Liverpool electrical visits run from L1 to L25 and take in city apartments, Georgian terraces, dock-edge commercial units and a lot of house shares. Bootle, Crosby, Wavertree-side streets and the blocks towards Mossley Hill do not share a single test method. A HMO with a lock on every bedroom needs the managing agent in the hallway or the dead-test stops at the first locked door. Hospitality sites near the waterfront often have a cellar board that is not on the landlord’s drawing. Birkenhead and Wallasey are across the water and are not described as Liverpool. Liverpool City Council governs the city. This business does not hold itself out as the council’s contractor.',
        'Warrington' => 'Warrington electrical work is dominated by logistics warehouses, Birchwood business-park suites and the newer housing at Great Sankey, plus older streets in WA1 to WA5. Lymm and Culcheth are booked as themselves. A warehouse with a mezzanine office has two supplies more often than the enquiry admits, and the mezzanine is where the overloaded sockets usually are. Newton-le-Willows instructions are not relabelled as Warrington. Runcorn and Widnes are close enough for a confused postcode, so the confirmation email repeats the unit number before travel. The report separates the office circuits from the warehouse lighting. Warrington Borough Council governs the borough. No framework or civic appointment is claimed. The office circuits are listed apart from the warehouse lighting on every sheet.',
    ];
}

/** @return array<string, string> */
function icomplyTier1GasArticles(): array
{
    return [
        'Stockport' => 'Letting agents around Hillgate, Edgeley and the SK2 to SK8 houses often ask for a landlord gas record before a new tenancy. That record is not produced by this office, and nobody from this firm attends to work on the boiler, the meter or the pipework. What can be booked for those same buildings is the electrical inspection and the fire-alarm attendance, including flats in Cheadle, Bramhall and Hazel Grove, once the access note lists who will be home. Romiley and Marple addresses are confirmed against the postcode rather than assumed from the word Stockport. The gas certificate, if the landlord needs one, has to come from a business that is allowed to issue it. This page is here so the wrong trade is not instructed.',
        'Manchester' => 'Manchester landlords of city-centre apartments and Victorian terraces frequently request a gas safety record at the same time as an inventory. This company will not carry out that gas task and will not hand over that certificate. M1 to M40 covers a wide mix of plant rooms; a high-rise with a communal boiler is a specialist gas job for a registered firm, not a line on our worksheet. What we can quote alongside the agent’s other compliance list is electrical testing and alarm servicing for Chorlton, Didsbury and the blocks the caretaker can actually open. Salford and Trafford postcodes are not quietly treated as Manchester. If the only thing required is the gas record, the instruction needs to go to a registered gas business.',
        'Salford' => 'MediaCity apartments and the newer blocks at M50 generate a steady demand for tenancy gas paperwork, as do the older houses in Eccles, Swinton and Walkden. This firm does not undertake that gas work and does not issue the paperwork. A communal plant room beside the ship canal is particularly easy to mis-instruct: the enquiry says “safety check” and means the gas appliances. We will say no to that part and, if wanted, price the corridor electrics if the client still wants that half of the building looked at. M3 and the M5–M7 houses are read for appliance type before anyone is promised a visit. Worsley and Irlam are not added to pad the area. A registered gas business has to produce the certificate.',
        'Trafford' => 'Altrincham, Sale, Stretford and Urmston landlords often bundle a gas record with an electrical test when a tenancy turns over. The gas half of that bundle is refused here. WA15 and WA14 Altrincham mail, Sale’s M33, Urmston’s M41 and Stretford’s M32 cover everything from a flat over an Altrincham shop to a business-park tea-point boiler. Neither is a job this company will do on the gas side. The electrical or alarm portion can still be quoted when the agent separates the scopes. Chorlton postcodes are not absorbed into Trafford. If the email only asks for the gas certificate, the reply points the sender to a registered gas business and stops there.',
        'Tameside' => 'Agents in Stalybridge, Dukinfield, Denton, Hyde and Ashton-under-Lyne regularly need a gas record for terraced lets and for flats over shops. Those emails show SK16, SK15, SK14 or an OL6 Ashton code. This office will not do the gas inspection and will not supply the certificate. Mossley and Droylsden enquiries get the same answer. Where the building also needs its electrical installation looked at, or the common-stair alarm serviced, that non-gas work can be scoped from the access notes. A mill conversion with a mix of domestic boilers and a commercial catering appliance is two different gas instructions for a registered firm, and neither sits on our job list. The page exists to stop the wrong purchase order.',
        'Oldham' => 'Terraced lets across OL1 to OL9, and the flats in Royton, Failsworth, Shaw, Lees and then Chadderton, are often between tenants when the gas record is requested. This company is not the business that attends the appliance or writes that record. A back-boiler still fitted in an older parlour house is a clear example of work that must go to a registered gas firm. We do not “have a look” while doing something else. If the same house needs its fuse board inspected or the smoke detection in the hallway checked as a fire-alarm question, those items can be quoted separately. Rochdale addresses are not renamed Oldham. Failsworth workshops with space heating are treated as commercial gas enquiries and declined.',
        'Bolton' => 'Bolton terraces, mill conversions and the houses in Horwich, Farnworth and Westhoughton produce a lot of pre-let gas paperwork requests, especially on BL1 to BL7. Those requests are turned away. A studio in a converted mill may have its own combi plus a landlord supply to a tea boiler on the corridor; both are gas and both are outside this firm’s work. The electrical test of that studio, or the alarm devices on the stair, can be priced if the client still wants them. Bury and Wigan borders cause mislabelled emails; the postcode decides, and the gas answer does not change. Radcliffe is not used as a synonym for Bolton. The certificate has to be issued by a registered gas business.',
        'Wigan' => 'Housing estates and older terraces on WN1 to WN6, together with Leigh lets, Hindley rows, Standish houses, Golborne shops and Ashton-in-Makerfield estates, are where Wigan letting lists usually ask for a gas record. This firm will not visit to create it. An estate house with a meter in an outside box and a warm-air cabinet in the lounge is a gas job for a registered engineer, including the question of whether the warm-air unit is still serviceable. We will not open that appliance. The electrical condition of the board, if still wanted, is a separate instruction from the gas refusal. Atherton postcodes are checked rather than assumed. No wording here should be read as an offer to do gas work.',
        'Liverpool' => 'Liverpool house-shares, Georgian terraces and dock-edge flats from L1 to L25 generate frequent demands for a tenancy gas record, often alongside the inventory. This company does not carry out that visit and does not issue the record. A HMO with a boiler in a locked cellar and hobs in four bedrooms is a gas scope for a registered firm, and the number of appliances matters to them, not to us. Bootle, Crosby and the streets towards Mossley Hill are not given a different answer. Birkenhead and Wallasey are not Liverpool. Electrical testing of the landlord’s distribution in those buildings can still be quoted. Hospitality sites with commercial kitchens are declined in full on the gas side.',
        'Warrington' => 'Birchwood suites, Great Sankey houses, Lymm lanes and Culcheth lets all appear on Warrington emails that ask for a gas certificate, under WA1–WA5. The answer is no. A logistics unit with a warehouse heater and a small office boiler is commercial gas plus a separate domestic-style appliance, and this firm does neither. Newton-le-Willows is not rewritten as Warrington to make the refusal shorter. Runcorn and Widnes enquiries are declined on the same ground. If the client also wants the office electrics inspected or the warehouse emergency lighting logged, that request can be split onto its own scope. The gas certificate itself must be obtained from a registered gas business. A second appliance in the warehouse does not change that refusal.',
    ];
}

/** @return array<string, string> */
function icomplyTier1FireArticles(): array
{
    return [
        'Stockport' => 'Stockport fire-alarm attendances are usually a Hillgate shop with rooms above, a small industrial bay, or a rented house where the insurer has asked for the panel log. Edgeley and the units off the A6 are typical. SK1 to SK8 reaches Cheadle Hulme as well as Bramhall, the Marple or Romiley end, and Hazel Grove, and each of those needs its own key schedule. A panel in a broom cupboard behind the till is a common find; the visit does not start until the zone chart on the cupboard door has been compared with the devices that are actually on the ceiling. Six-monthly servicing is booked only when the previous certificate is in the email, so the engineer knows whether conventional heads or an addressable loop is fitted. Poynton is included when the postcode says so. No council contract with Stockport Metropolitan Borough Council is implied.',
        'Manchester' => 'Manchester alarm work is split by building height more than by a single postcode. M1 to M40 runs from Deansgate residential towers to Victorian conversions in Chorlton and Didsbury. A tower needs the cause-and-effect notes for the smoke vents and the lift before the panel is touched. A terrace conversion often has a single conventional panel and a row of domestic-style detectors that were never commissioned as a system. Salford and Trafford instructions stay on their own pages. The engineer walks the zones with the chart, marks devices that are painted over, and does not invent a category the building was never designed to. The city is run by Manchester City Council. This firm is not appointed by it. Insurer packs from city agents usually want the logbook pages, not a marketing claim.',
        'Salford' => 'Salford alarm visits concentrate on MediaCity offices, M50 apartments and the older blocks towards Eccles, Swinton and Walkden. Booking forms show M50, or an M3 office, or an M6 or M7 house, sometimes M5. A quayside office often interfaces the fire panel with door magnets and plant shutdown, so the test is agreed with the facilities manager before any magnet is released. A Walkden terrace with a rented flat is a much smaller panel and should not be written up as if it were the quayside. Worsley and Irlam are only attended when named. The sheet lists devices that failed to sound and the ones that could not be reached because a suite was locked. Salford City Council is not the client unless a real order says so. No civic framework is advertised.',
        'Trafford' => 'Trafford fire-alarm diaries move between Altrincham offices, Sale apartment stairs, Stretford parades and Urmston shops. Sale one morning and Altrincham the next, using the postcode on the order rather than one combined list. A Stretford parade shop can have a panel that only covers the shop, leaving the upstairs flat on domestic detectors; the report says so instead of implying one system. Commercial-park units often share a landlord panel in a service corridor that several tenants have never seen. Chorlton is adjacent and is not silently included. The engineer needs the zone list before releasing any door holder. Trafford Council governs that borough. Attendance on a private building is not a council inspection and is not described as one.',
        'Tameside' => 'Tameside alarm work is biased toward terraces and small factories in Hyde, then Denton bays, Dukinfield shops, Stalybridge hills and Ashton-under-Lyne terraces. Orders carry Ashton OL codes or the SK14–SK16 side, with Mossley and Droylsden when the portfolio says those towns. A mill floor subdivided into workshops may have one panel and several locked suites, so the test records the suites that were refused rather than copying last year’s zone count. Shop units on a town-centre rank often have the panel in the basement of a different unit. The cause-and-effect, where any exists, is read from the panel notes, not assumed. Tameside Metropolitan Borough Council is the named authority. This page does not offer a council-backed scheme.',
        'Oldham' => 'Oldham fire-alarm calls are typically a terrace landlord, a small warehouse, or a town-centre unit in OL1 to OL9. Shaw yards differ from Lees stairs, and Failsworth units differ again from Royton or Chadderton. A warehouse with racking needs the detector positions checked against the aisle layout, because a later fit-out often leaves heads above the steel rather than the escape route. Painted-over call points show up in the older streets. Rochdale is a neighbour and is not described as part of this borough. The log records sound-pressure only where it was actually measured, and silence where a tenant would not allow the bells. Oldham Council governs this borough. No civic tie is stated.',
        'Bolton' => 'Bolton alarm servicing lands on terraces, retail parks and mill floors across BL1 to BL7, plus Horwich, Farnworth and Westhoughton as separate sites. A mill split into studios can have an addressable loop that was extended by three fit-outs, so the device count on the original certificate is treated as history, not fact. The engineer addresses the devices that answer and lists the ones that do not. A retail-park unit with a mezzanine often has no detector under the mezzanine; that gap is written down. Bury and Wigan are outside this borough’s page. Radcliffe is attended only on its own postcode. Bolton Council remains the authority, and a private service visit is not one of its inspections.',
        'Wigan' => 'Wigan fire-alarm appointments follow estates and industrial streets on WN1 to WN6, and named sites in Standish, then Golborne, then Hindley, Leigh is added only when the paperwork names it, and the Makerfield town only when it is written in full. An estate community room with a small conventional panel is a different visit from a factory that releases roller shutters on fire. The shutter interface is tested only with the occupier’s permission and a person at the door. Atherton instructions are matched to the postcode because portfolios mis-file them under Wigan or Bolton. Sounders in a noisy workshop are noted as heard or not heard from the positions walked, not from the car park. Wigan Council governs that borough. The visit is a contractor’s service, not a civic audit.',
        'Liverpool' => 'Liverpool alarm work covers L1 to L25: house-shares with a landlord panel, Georgian conversions, dock-side commercial units and hospitality cellars. Bootle and Crosby are common; Birkenhead and Wallasey are not this city and are not written up as if they were. A HMO panel in a hallway cupboard is often conventional and missing a zone chart. A waterfront unit may interface magnet doors across a long corridor, and those doors are listed individually. The engineer does not claim a category the design never had. Mossley Hill houses with a single stair are described from the stair that was walked. Liverpool City Council runs the city. This firm is not its inspector.',
        'Warrington' => 'Warrington fire-alarm sites are mostly dock-style sheds, suites on the Birchwood parks and common rooms at Great Sankey, with older central streets whose codes sit in the WA1–WA5 block. Lymm and Culcheth are their own instructions. A warehouse panel may shut down a shutter and a mezzanine extract fan; both actions are confirmed with the shift manager before the test, because a loaded dock cannot be closed by surprise. Office suites on a business park often sit on a landlord loop the tenant has never seen. Newton-le-Willows is not renamed to stretch the town. Runcorn and Widnes stay off this page unless the postcode is wrong and gets corrected. Warrington Borough Council is not the contractor on these private panels.',
    ];
}

/** @return array<string, string> */
function icomplyTier1LightingArticles(): array
{
    return [
        'Stockport' => 'Emergency lighting in Stockport is usually a stair in a flat conversion, a shop floor on Hillgate, or a small factory unit off the A6. Within SK1–SK8 the Romiley and Marple fittings differ from Hazel Grove and from Bramhall, and Cheadle is only on the list when the key is there. Those fittings are often a mix of old bulkheads and newer LED units on the same circuit. The test is a discharge of the fittings that can be found, timed against the duration the luminaire claims on its label, not against a brochure. A painted diffuser in an Edgeley stair is opened only when the fixings allow it. Keys for a first-floor office over a shop have to include the shop alarm code or the test stops at the lobby. Poynton is added from the postcode. Results are a log of pass, fail and not-found, which is what an insurer in this town has actually asked for.',
        'Manchester' => 'Manchester emergency-lighting tests vary with the core of the building. In a Deansgate tower the fittings sit in a long corridor and a stair that the caretaker must unlock floor by floor, across parts of M1 to M40. In a Chorlton or Didsbury conversion they are two bulkheads on a single stair and easy to miss on a drawing. High-rise tests are booked with a start floor and a finish floor so a three-hour discharge is not attempted in a lunch break. Fittings above a suspended ceiling in an office are listed as unseen if the tile cannot be lifted. Salford and Trafford cores are not walked under a Manchester heading. The log names the stair, not “the building”. Manchester City Council is not the commissioning body for a private block.',
        'Salford' => 'Salford emergency lighting shows up in MediaCity corridors, M50 apartment stairs and the older common ways in Eccles, Swinton and Walkden. M3 and M5 to M7 add further landlord stairs. A quayside office may use self-test fittings whose panel history the facilities manager can export; the visit still spot-checks a sample because a green LED is not a duration test. A Walkden house conversion usually has non-maintained bulkheads with no self-test at all. Worsley and Irlam are scheduled only when the address says so. Fittings in a car-park stair that are wet are noted as such before anyone quotes a replacement. Salford City Council does not write this logbook. Wet car-park fittings stay in the notes even when they are left untouched.',
        'Trafford' => 'Trafford duration tests move from Altrincham office stairs to Sale apartment landings, Stretford shop escapes and Urmston parade stores. An Urmston store (M41) is not a Sale landing (M33) and neither is an Altrincham stair on WA14. A parade shop often has one illuminated exit sign and nothing on the rear stair to the flat; the log says “rear stair, no fitting” rather than a pass. The extra line on the sheet is the floor, not a copied address list. Commercial-park corridors can have maintained fittings that are also the only normal light, so a discharge plunges the corridor dark and has to be agreed. Chorlton is not rolled in. Failed batteries are identified by location, not by a count alone. Trafford Council does not commission these private tests.',
        'Tameside' => 'Tameside emergency-lighting walks are Denton mills, Dukinfield terraces, Hyde shops, the ridge above Stalybridge and the streets through Ashton-under-Lyne. Codes on the sheet are Ashton OL numbers or the SK14–SK16 side of the borough. Mossley and Droylsden appear on mixed portfolios. A mill stair can have fittings so high that the lamp type is unreadable without a tower; those are logged as high-level, not as tested. Workshop units sometimes use the emergency fitting as a night light, which flattens the battery before the annual test. The engineer asks whether that practice is still happening. A town-centre shop with a basement stockroom needs the basement key or the stockroom is “not entered”. Tameside Metropolitan Borough Council is not the tester.',
        'Oldham' => 'Oldham emergency lighting is concentrated in terraced conversions and small warehouses across OL1 to OL9, plus a Failsworth yard, a Shaw lane, a Lees terrace, a Royton shop and a Chadderton ginnel. A warehouse aisle that was re-racked last year often leaves the old fitting pointing at steel instead of the exit. The test records the aim as found. House conversions on steep streets have a stair bulkhead that has been covered by a later false ceiling; if it cannot be seen it is not marked as a pass. Rochdale sites stay on Rochdale instructions. Wet fittings in a yard passage are photographed for the quote and left in place. Oldham Council is not the client on these private logs.',
        'Bolton' => 'Bolton emergency-lighting tests cover mill stairs, retail-park service corridors and house conversions on BL1 to BL7, with separate visits in Horwich, Farnworth and Westhoughton. A mill studio floor may have maintained LED panels that also light the desk, so the discharge has to be timed when the occupier can stop work. A retail-park corridor shared by three units needs the landlord present or two of the doors stay shut and untested. The sheet distinguishes “door locked” from “fitting failed”. Bury and Wigan are not used as alternate names. Radcliffe keeps its own postcode. Bolton Council is not the organisation signing the log. A mezzanine with no fitting underneath is written as a gap, not inferred from the corridor.',
        'Wigan' => 'Wigan duration testing follows WN1 to WN6 estates, community rooms and industrial units, plus Leigh halls, Hindley stairs, Standish landings, Golborne retail units and the landings in the Makerfield town when those are the addresses. A second fitting at the bottom of the stair is easy to miss and is written as its own line. A community hall with a stage has fittings over the stage that the weekly user test never reaches; the annual visit includes them if a ladder is allowed. Factory mezzanines often have a single unit at the top of an open stair and none at the bottom. Atherton is checked against the postcode because agents file it under two boroughs. Results are written per fitting location. Wigan Council does not employ this firm to act as its lighting inspector.',
        'Liverpool' => 'Liverpool emergency lighting ranges from HMO stairs and Georgian conversions to dock warehouses and hospitality cellars, across L1 to L25. Bootle and Crosby are frequent; Wallasey and Birkenhead are not given Liverpool log sheets. A house-share stair with two bulkheads is a short test. A cellar bar with maintained signs over several changes of level needs the manager on site because the discharge affects trading light. Fittings hidden above a keg rack are “not reached” if moving the rack is refused. Mossley Hill houses are walked from the stair that exists, not from a plan of a different house. Liverpool City Council is not the author of these private logs.',
        'Warrington' => 'Warrington emergency-lighting work is mostly escape routes inside logistics sheds, cores on the Birchwood office parks and stairs in the newer Great Sankey blocks, mixed with older central buildings whose mail codes start WA. Lymm and Culcheth are booked separately. A logistics warehouse may have high-bay emergency fittings that need the scissor lift the site already owns; without that lift the lamps are “seen from floor, not opened”. Office cores on the business parks are often self-test and still get a manual discharge of a sample. Newton-le-Willows is not absorbed into the town name. Runcorn and Widnes keep their own instructions. These private tests are not commissioned by Warrington Borough Council. The sample discharge is still done by hand even where a self-test lamp shows green.',
    ];
}
