<?php
/**
 * Twelve quality SEO hubs (Batch C). Not doorway spam, not HMO package landings.
 */
declare(strict_types=1);

/**
 * @return array<string,array<string,mixed>>
 */
function wave1QualityHubs(): array
{
    return [
        'landlord-certificates' => [
            'navLabel' => 'Landlord certificates',
            'pageTitle' => 'Landlord Certificates | EICR, Gas, FRA & Alarms',
            'metaDesc' => 'Landlord certificates from a Stockport SK2 contractor — EICR, gas safety records, fire risk assessments, smoke/CO and EPCs. Scoped quotes only; no published price list.',
            'metaKeywords' => 'landlord certificates, landlord compliance pack, EICR gas FRA landlords North West, Stockport landlord certificates',
            'ogImage' => '/assets/images/services/landlord-compliance.jpg',
            'kicker' => 'Quality hub · Landlords',
            'crumb' => 'Landlord certificates',
            'h1' => 'Landlord certificates',
            'h1Accent' => 'one file, honest scope',
            'lede' => 'The documents agents, tenants and licensing officers ask for — quoted after we know the house, not copied from a national price grid.',
            'honest' => 'We issue records for the inspections and installs we complete. We do not grant licences, give legal advice, or publish invented package prices.',
            'coverTitle' => 'The certificates a let file usually holds',
            'cover' => [
                'Most single lets in England revolve around a current [EICR](/pages/services/electrical), a [gas safety record](/pages/services/gas-systems) where gas is present, working [smoke and CO alarms](/pages/services/smoke-co-alarms), and a valid [EPC](/pages/services/epc) if you are marketing the property.',
                'Shared houses and blocks add [fire risk assessment](/pages/services/fire-risk-assessments) and often alarms, lighting or doors. Those extras belong on the FRA and the licence conditions — not on a one-size web bundle.',
            ],
            'work' => [
                'Electrical installation condition reports and agreed remedials',
                'Landlord gas safety records and optional boiler service on the same visit',
                'Smoke / CO alarm supply, siting and day-of-let testing notes',
                'Domestic EPCs for marketing a let',
                'FRA and follow-on fire work when the house is shared or has common parts',
            ],
            'whoTitle' => 'Who uses this hub',
            'who' => [
                ['title' => 'Private landlords', 'text' => 'One or many doors, self-managing or with an agent who wants a complete file before keys.'],
                ['title' => 'Letting agents', 'text' => 'Voids and renewals where several certificates fall due in the same fortnight.'],
                ['title' => 'Small portfolios', 'text' => 'A single point of contact from the SK2 yard instead of four separate contractors.'],
            ],
            'relatedGuides' => ['gas-safety-certificate-landlords', 'let-ready-void-checklist', 'electrical-safety-rented-homes'],
            'formService' => 'Landlord certificates',
            'formHeading' => 'Request a landlord-file quote',
            'formIntro' => 'List the certificates you already have. We only quote what is due.',
            'formPlaceholder' => 'Address, tenure, last EICR / gas / EPC / FRA dates…',
            'faqs' => [
                ['q' => 'Do you sell a fixed “landlord pack” price?', 'a' => 'No. Houses differ. Ask for a written quote. Existing Let Ready and workplace packages stay on their own pages — we are not duplicating HMO package landings here.'],
                ['q' => 'Is this legal advice?', 'a' => 'No. It is practical inspection and documentation for your file.'],
            ],
        ],
        'gas-safety-certificate' => [
            'navLabel' => 'Gas safety certificate',
            'pageTitle' => 'Gas Safety Certificate | Landlord CP12 North West',
            'metaDesc' => 'Landlord gas safety certificates (CP12 / gas safety records) across Greater Manchester from Stockport SK2. Gas Safe engineers, written records, quote after appliance count.',
            'metaKeywords' => 'gas safety certificate, CP12 Stockport, landlord gas safety Greater Manchester, CP44 gas record',
            'ogImage' => '/assets/images/services/gas-systems.jpg',
            'kicker' => 'Quality hub · Gas',
            'crumb' => 'Gas safety certificate',
            'h1' => 'Gas safety certificate',
            'h1Accent' => 'landlord records, written straight',
            'lede' => 'A Gas Safe visit, a record that matches the appliances on site, and a quote that waits until we know how many there are.',
            'honest' => 'Engineers are Gas Safe registered for the work we accept. Unsafe appliances stay unsafe on the record. No published per-appliance web price.',
            'coverTitle' => 'The landlord gas record, not a service sticker',
            'cover' => [
                'Private landlords with gas appliances or flues generally need a periodic safety check and a written record for the tenancy. People still call it a CP12. The file needs the current record, not a verbal “it was fine last year”.',
                'Read the fortnight guide: [gas safety certificate for landlords](/pages/resources/gas-safety-certificate-landlords). Service page: [gas systems](/pages/services/gas-systems).',
            ],
            'work' => [
                'Landlord gas safety records for houses, flats and shared lets',
                'Optional boiler service on the same attendance when you ask for it',
                'Clear outcome if an appliance fails — isolation and next-step quote, not a rewritten pass',
            ],
            'whoTitle' => 'Typical bookings',
            'who' => [
                ['title' => 'Annual renewals', 'text' => 'The record is coming up to twelve months and the agent wants it before the reminder letter.'],
                ['title' => 'Voids', 'text' => 'Keys back, gas still live, new tenancy in days.'],
                ['title' => 'Portfolios', 'text' => 'Several addresses in one GM cluster so travel is not the whole day.'],
            ],
            'relatedGuides' => ['gas-safety-certificate-landlords', 'let-ready-void-checklist', 'booking-compliance-certificates'],
            'formService' => 'Gas — landlord safety record',
            'formHeading' => 'Request a gas-record quote',
            'formIntro' => 'Appliance count and access decide the visit. Send those first.',
            'formPlaceholder' => 'Postcode, appliances, occupied or void…',
            'faqs' => [
                ['q' => 'CP12 or CP44?', 'a' => 'You will hear both. What matters is a current landlord gas safety record that lists the appliances we checked.'],
                ['q' => 'Do you cover Manchester as well as Stockport?', 'a' => 'Yes, when we can resource the diary. The yard is Offerton SK2.'],
            ],
        ],
        'fire-risk-assessment' => [
            'navLabel' => 'Fire risk assessment',
            'pageTitle' => 'Fire Risk Assessment | Landlords & Workplaces',
            'metaDesc' => 'Fire risk assessments for rented, shared and commercial buildings in the North West. Written FRA and action plan from Stockport SK2. Quote after we know the premises.',
            'metaKeywords' => 'fire risk assessment, FRA Stockport, commercial FRA Manchester, landlord fire risk assessment',
            'ogImage' => '/assets/images/services/fire-risk-assessments.jpg',
            'kicker' => 'Quality hub · Fire',
            'crumb' => 'Fire risk assessment',
            'h1' => 'Fire risk assessment',
            'h1Accent' => 'written for this building',
            'lede' => 'A suitable and sufficient FRA describes your premises and the people in them — then a prioritised action list you can actually schedule.',
            'honest' => 'An FRA is not a licence, not legal advice, and not a guarantee of enforcement outcomes. Follow-on fire work is quoted separately unless you asked us to include it.',
            'coverTitle' => 'Assessment first, kit second',
            'cover' => [
                'We walk the building, record hazards and existing precautions, and write the assessment. If detection, lighting or doors are short, you get an action list — and a separate quote if you want us to do that work.',
                'Guide: [fire risk assessments explained](/pages/resources/fire-risk-assessment-guide). Service: [fire risk assessments](/pages/services/fire-risk-assessments).',
            ],
            'work' => [
                'Written FRA for lets with common parts, shared houses, offices and other workplaces',
                'Action plans that distinguish management tasks from physical upgrades',
                'Optional follow-on quotes for alarms, emergency lighting, doors and extinguishers',
            ],
            'whoTitle' => 'Who commissions an FRA here',
            'who' => [
                ['title' => 'Landlords & agents', 'text' => 'Shared houses, conversions and blocks where a single-let checklist is the wrong document.'],
                ['title' => 'Employers & FM', 'text' => 'Offices, shops and industrial units that need a current workplace assessment.'],
                ['title' => 'Care operators', 'text' => 'Sleeping risk and staffing change the plan — say so up front.'],
            ],
            'relatedGuides' => ['fire-risk-assessment-guide', 'commercial-fire-safety-basics', 'fire-door-inspection'],
            'formService' => 'Fire risk assessment',
            'formHeading' => 'Request an FRA quote',
            'formIntro' => 'Storeys, use and sleeping risk first. Then a written figure.',
            'formPlaceholder' => 'Address, use, storeys, last FRA date…',
            'faqs' => [
                ['q' => 'Do you grant HMO licences?', 'a' => 'No. Licensing is the local authority. We produce practical fire documentation and related trade work.'],
                ['q' => 'Will you copy last year’s FRA and change the date?', 'a' => 'No. If the building has not changed we still review it; we do not sell a re-dated PDF.'],
            ],
        ],
        'electrical-safety-landlords' => [
            'navLabel' => 'Electrical safety',
            'pageTitle' => 'Electrical Safety for Landlords | EICR North West',
            'metaDesc' => 'Electrical safety for landlords in Greater Manchester — EICR inspections, C1–C3 remedials and honest quotes from Stockport SK2. Not PAT and not an EPC.',
            'metaKeywords' => 'landlord EICR, electrical safety landlords, EICR Stockport Manchester, C1 C2 electrical remedials',
            'ogImage' => '/assets/images/services/electrical.jpg',
            'kicker' => 'Quality hub · Electrical',
            'crumb' => 'Electrical safety',
            'h1' => 'Electrical safety',
            'h1Accent' => 'for landlords',
            'lede' => 'A satisfactory EICR is the document the tenancy file wants. Remedials are quoted as found — not buried in a surprise invoice.',
            'honest' => 'The report describes condition on the inspection day. We do not guarantee five quiet years, and we do not sell a pass without the visit.',
            'coverTitle' => 'Fixed installation, coded report',
            'cover' => [
                'We inspect and test the fixed installation against BS 7671 practice and issue a coded EICR. If C1 or C2 items appear, you get a remedial quote. C3 items are listed as improvements, not automatically a failed let.',
                'Guides: [EICR](/pages/resources/eicr-guide) and [electrical safety in rented homes](/pages/resources/electrical-safety-rented-homes). Service: [electrical](/pages/services/electrical).',
            ],
            'work' => [
                'Landlord and commercial EICRs',
                'Remedial works and consumer-unit upgrades when you instruct them',
                'Optional PAT on the same access window for furnished lets',
            ],
            'whoTitle' => 'Typical electrical bookings',
            'who' => [
                ['title' => 'Five-year renewals', 'text' => 'The last report is ageing out and the agent will not relist without a new one.'],
                ['title' => 'Change of tenancy', 'text' => 'Void access, one visit, report into the new file.'],
                ['title' => 'Unsatisfactory follow-up', 'text' => 'Someone else left C2s. You want them closed and a satisfactory outcome recorded.'],
            ],
            'relatedGuides' => ['electrical-safety-rented-homes', 'pat-testing-guide', 'eicr-guide'],
            'formService' => 'Electrical — EICR',
            'formHeading' => 'Request an EICR quote',
            'formIntro' => 'Boards, occupancy and property type — then a written quote.',
            'formPlaceholder' => 'House / flat / HMO, consumer units, last EICR date…',
            'faqs' => [
                ['q' => 'Is this the same as PAT?', 'a' => 'No. PAT is appliances. The EICR is the fixed wiring and accessories.'],
                ['q' => 'Do you publish EICR fees?', 'a' => 'No. Circuit count and access change the job.'],
            ],
        ],
        'commercial-fire-safety' => [
            'navLabel' => 'Commercial fire safety',
            'pageTitle' => 'Commercial Fire Safety | Alarms, Lighting & FRA',
            'metaDesc' => 'Commercial fire safety for FM teams in the North West — FRA, fire alarms, emergency lighting, doors and extinguishers. Stockport-based; scoped quotes only.',
            'metaKeywords' => 'commercial fire safety, workplace fire alarms, emergency lighting servicing, FM fire safety North West',
            'ogImage' => '/assets/images/services/fire-alarms.jpg',
            'kicker' => 'Quality hub · Commercial',
            'crumb' => 'Commercial fire safety',
            'h1' => 'Commercial fire safety',
            'h1Accent' => 'for workplaces and FM',
            'lede' => 'Keep the FRA current, service the alarm, test the lighting, look after the doors. That is the programme most sites actually need.',
            'honest' => 'We maintain and install the systems we quote. We do not sell a fake accreditation wall or a one-line national retainers price.',
            'coverTitle' => 'A workplace fire programme, not a gadget list',
            'cover' => [
                'Start with the [FRA](/pages/fire-risk-assessment), then book the systems it names. Most offices and industrial units live on [fire alarm servicing](/pages/resources/fire-alarm-servicing) and [emergency lighting testing](/pages/resources/emergency-lighting-testing). Where the building has a stair vent, shaft or smoke fan, [AOV and smoke control](/pages/services/aov-air-handling) is part of that fire-protection set and is quoted across the UK from Stockport. Travel outside a short North West run is on the quote.',
                'Audience page: [commercial / FM](/pages/commercial). Guide: [commercial fire safety basics](/pages/resources/commercial-fire-safety-basics).',
            ],
            'work' => [
                'Fire alarm install, service and logbook visits',
                'Emergency lighting monthly / annual testing and upgrades',
                'Fire door surveys and extinguisher servicing when the FRA wants them',
                'Kitchen suppression quotes for catering sites',
            ],
            'whoTitle' => 'Who this hub is for',
            'who' => [
                ['title' => 'Facilities managers', 'text' => 'Several sites, mixed kit brands, a diary that cannot absorb three no-shows.'],
                ['title' => 'Managing agents', 'text' => 'Common parts in mixed-use blocks — alarm, lighting, doors, FRA.'],
                ['title' => 'Owner-occupiers', 'text' => 'A single workshop or office that still needs a competent person, not a DIY sticker.'],
            ],
            'relatedGuides' => ['commercial-fire-safety-basics', 'fire-alarm-servicing', 'emergency-lighting-testing'],
            'formService' => 'Commercial fire safety',
            'formHeading' => 'Request a workplace fire quote',
            'formIntro' => 'Tell us the kit you already have. Unknown panels are why quotes wait for a photo.',
            'formPlaceholder' => 'Site type, panel brand, last service / FRA dates…',
            'faqs' => [
                ['q' => 'Is this the Fire Ready package?', 'a' => 'No. Fire Ready stays on its package page. This hub is the quality commercial landing.'],
                ['q' => 'Do you take over orphaned systems?', 'a' => 'Often, after we see the panel and any cause-and-effect. That survey is part of quoting, not a free design for a third party.'],
            ],
        ],
        'smoke-carbon-monoxide-alarms' => [
            'navLabel' => 'Smoke & CO alarms',
            'pageTitle' => 'Smoke & Carbon Monoxide Alarms | Landlords',
            'metaDesc' => 'Smoke and carbon monoxide alarms for rented homes in England — supply, siting and day-of-let testing notes. Quote from Stockport; wider fire systems when the house needs them.',
            'metaKeywords' => 'smoke alarms landlords, carbon monoxide alarms, CO alarm installation, landlord smoke alarm Stockport',
            'ogImage' => '/assets/images/services/smoke-co-alarms.jpg',
            'kicker' => 'Quality hub · Alarms',
            'crumb' => 'Smoke and CO alarms',
            'h1' => 'Smoke and CO alarms',
            'h1Accent' => 'sited, tested, recorded',
            'lede' => 'Working alarms in the right rooms, tested when the tenancy starts — and a grown-up fire system when a handful of domestics is the wrong answer.',
            'honest' => 'England private-rented alarm rules are not the same as a BS 5839 HMO design. We will say which conversation you are in.',
            'coverTitle' => 'Domestic alarms versus a designed system',
            'cover' => [
                'Many single lets need storey smoke coverage and CO alarms where a fixed combustion appliance sits. Shared houses and licence conditions often need [fire alarms](/pages/services/fire-alarms) instead.',
                'Guide: [smoke and CO alarms](/pages/resources/smoke-and-co-alarms). Service: [smoke-co-alarms](/pages/services/smoke-co-alarms).',
            ],
            'work' => [
                'Supply and siting of smoke and CO alarms',
                'Replacement of life-expired sealed units',
                'Day-of-let test notes for the tenancy file',
                'Honest step-up to a designed fire-alarm quote when the layout demands it',
            ],
            'whoTitle' => 'Who books this',
            'who' => [
                ['title' => 'Re-lets', 'text' => 'Alarms missing, chirping, or past the printed end-of-life date.'],
                ['title' => 'New landlords', 'text' => 'First file, unsure what “each storey” means on a split-level conversion.'],
                ['title' => 'Agents', 'text' => 'A consistent spec across a small portfolio without overselling panels.'],
            ],
            'relatedGuides' => ['smoke-and-co-alarms', 'let-ready-void-checklist', 'fire-risk-assessment-guide'],
            'formService' => 'Smoke and CO alarms',
            'formHeading' => 'Request an alarm quote',
            'formIntro' => 'Storeys and existing detectors first. We will not upsell a panel you do not need.',
            'formPlaceholder' => 'Storeys, rooms, gas appliances, existing alarms…',
            'faqs' => [
                ['q' => 'Do you fit interlinked alarms?', 'a' => 'Yes when the layout or the FRA wants them. Say what is already there.'],
                ['q' => 'Is this an HMO fire-alarm package?', 'a' => 'No. HMO package landings live on PR #3 and are not duplicated here.'],
            ],
        ],
        'portable-appliance-testing' => [
            'navLabel' => 'PAT testing',
            'pageTitle' => 'PAT Testing | Landlords & Workplaces North West',
            'metaDesc' => 'PAT testing for furnished lets and workplaces in the North West. Portable appliances only — not an EICR. Quote after an approximate item count.',
            'metaKeywords' => 'PAT testing Stockport, portable appliance testing Manchester, landlord PAT, workplace PAT testing',
            'ogImage' => '/assets/images/services/pat-testing.jpg',
            'kicker' => 'Quality hub · PAT',
            'crumb' => 'PAT testing',
            'h1' => 'PAT testing',
            'h1Accent' => 'the plug-in list',
            'lede' => 'Inspect and test landlord-owned or workplace appliances. Fail the dangerous ones. Leave the fixed installation to the EICR.',
            'honest' => 'There is no universal legal “every 12 months” for every toaster in England. Frequency is risk-based unless your insurer or client specifies one.',
            'coverTitle' => 'Appliances, labelled and listed',
            'cover' => [
                'We inspect and, where justified, test portable equipment and issue a pass / fail list. Combined visits with an [EICR](/pages/electrical-safety-landlords) are common on voids.',
                'Guide: [PAT testing](/pages/resources/pat-testing-guide). Service: [PAT testing](/pages/services/pat-testing).',
            ],
            'work' => [
                'Furnished-let appliance lists',
                'Office, workshop and small industrial PAT',
                'Failed-item isolation advice and retest when you replace the kit',
            ],
            'whoTitle' => 'Who asks for PAT',
            'who' => [
                ['title' => 'Agents', 'text' => 'Furnished lets where landlord white goods sit in the inventory.'],
                ['title' => 'Employers', 'text' => 'A workplace that wants a current appliance register.'],
                ['title' => 'Landlords after an EICR', 'text' => 'The report was about wiring; the kettle still needs its own conversation.'],
            ],
            'relatedGuides' => ['pat-testing-guide', 'electrical-safety-rented-homes', 'let-ready-void-checklist'],
            'formService' => 'PAT testing',
            'formHeading' => 'Request a PAT quote',
            'formIntro' => 'A rough count is enough. We refine on site.',
            'formPlaceholder' => 'Site type, approximate appliance count, access hours…',
            'faqs' => [
                ['q' => 'Will PAT make an unsatisfactory EICR satisfactory?', 'a' => 'No. Different documents, different kit.'],
                ['q' => 'Do you test tenant-owned hairdryers?', 'a' => 'Not as a default. Say if a workplace rule or inventory requires it.'],
            ],
        ],
        'energy-performance-certificates' => [
            'navLabel' => 'EPC',
            'pageTitle' => 'EPC for Landlords & Commercial | North West',
            'metaDesc' => 'Energy Performance Certificates for lets and commercial units in the North West. Domestic and non-domestic assessments, quote after floor area. Not a gas or EICR certificate.',
            'metaKeywords' => 'EPC landlords, commercial EPC, energy performance certificate Stockport, EPC Manchester',
            'ogImage' => '/assets/images/services/epc.jpg',
            'kicker' => 'Quality hub · EPC',
            'crumb' => 'Energy Performance Certificates',
            'h1' => 'Energy Performance Certificates',
            'h1Accent' => 'to let or to market',
            'lede' => 'A modelled rating so you can advertise a let or a commercial unit. It does not prove the boiler or the wiring is safe this year.',
            'honest' => 'Certificates usually last ten years unless you change the building. Minimum rental bands can change — confirm the current England and Wales threshold; we do not freeze a political target in a headline.',
            'coverTitle' => 'The right methodology for the building',
            'cover' => [
                'Houses and flats use the domestic model. Shops and offices often need non-domestic. We will not force the cheaper methodology onto the wrong building.',
                'Guide: [EPCs for landlords](/pages/resources/epc-for-landlords). Service: [EPC](/pages/services/epc).',
            ],
            'work' => [
                'Domestic EPCs for private rented marketing',
                'Non-domestic EPCs for commercial units',
                'Same-access planning with other void certificates when you ask',
            ],
            'whoTitle' => 'When people book an EPC',
            'who' => [
                ['title' => 'New instructions', 'text' => 'The agent will not list without a certificate number.'],
                ['title' => 'Expired ratings', 'text' => 'The last EPC has aged out of its ten-year window.'],
                ['title' => 'After works', 'text' => 'Insulation, heating or glazing changed enough that the old model is untrue.'],
            ],
            'relatedGuides' => ['epc-for-landlords', 'let-ready-void-checklist', 'booking-compliance-certificates'],
            'formService' => 'EPC',
            'formHeading' => 'Request an EPC quote',
            'formIntro' => 'Domestic or commercial, and a sense of floor area.',
            'formPlaceholder' => 'Dwelling or commercial, floor area, last EPC date…',
            'faqs' => [
                ['q' => 'Does an EPC replace a gas safety record?', 'a' => 'No. Completely different documents.'],
                ['q' => 'Can you guarantee a C rating?', 'a' => 'No. The model reports the building as found. Improvement works are a separate quote.'],
            ],
        ],
        'fire-door-compliance' => [
            'navLabel' => 'Fire door compliance',
            'pageTitle' => 'Fire Door Compliance | Survey & Remedials',
            'metaDesc' => 'Fire door surveys and remedials for landlords and FM in the North West — seals, closers, gaps and honest replace-versus-repair advice. Quote after a door count.',
            'metaKeywords' => 'fire door survey, fire door compliance, fire door closer, intumescent seals North West',
            'ogImage' => '/assets/images/services/fire-doors.jpg',
            'kicker' => 'Quality hub · Fire doors',
            'crumb' => 'Fire door compliance',
            'h1' => 'Fire door compliance',
            'h1Accent' => 'survey, then honest remedials',
            'lede' => 'Check the doorsets the FRA named. Repair what can be repaired. Replace what was never a fire door.',
            'honest' => 'A seal kit does not turn a hollow-core leaf into a fire doorset. We will say that even if it costs us a small job.',
            'coverTitle' => 'Doorsets on the escape plan',
            'cover' => [
                'The FRA should say which doors are fire doors. We inspect those doorsets — leaf, frame, seals, hinges, glazing, closer — and quote remedials or replacements.',
                'Guide: [fire door inspection](/pages/resources/fire-door-inspection). Service: [fire doors](/pages/services/fire-doors).',
            ],
            'work' => [
                'Condition surveys with a defect list',
                'Seals, closers and ironmongery where the leaf and frame are still suitable',
                'Doorset replacement when the core or frame was never rated',
            ],
            'whoTitle' => 'Who books door work',
            'who' => [
                ['title' => 'After an FRA', 'text' => 'The action plan lists doors. You want one contractor to close the list.'],
                ['title' => 'Blocks & conversions', 'text' => 'Flat entrance doors and protected stairs that have been planed or re-ironed over the years.'],
                ['title' => 'Workplaces', 'text' => 'Stair and kitchen doors that no longer latch.'],
            ],
            'relatedGuides' => ['fire-door-inspection', 'fire-risk-assessment-guide', 'commercial-fire-safety-basics'],
            'formService' => 'Fire doors',
            'formHeading' => 'Request a fire-door quote',
            'formIntro' => 'Door count and building type. Photos of the closest and the worst door help.',
            'formPlaceholder' => 'How many doors, FRA already done?, known defects…',
            'faqs' => [
                ['q' => 'Can you certificate a door I planed last year?', 'a' => 'We can survey it. If the gaps and lipping are gone, the honest answer is replace, not a new sticker.'],
                ['q' => 'Do all house doors need to be fire doors?', 'a' => 'No. Layout and the FRA decide.'],
            ],
        ],
        'emergency-lighting-compliance' => [
            'navLabel' => 'Emergency lighting',
            'pageTitle' => 'Emergency Lighting Compliance | Testing & Upgrades',
            'metaDesc' => 'Emergency lighting testing and upgrades for HMOs, blocks and workplaces in the North West. Monthly function and annual duration tests, logbooks, quote after a walk of the escape.',
            'metaKeywords' => 'emergency lighting testing, BS 5266, emergency lighting service North West, annual duration test',
            'ogImage' => '/assets/images/services/emergency-lighting.jpg',
            'kicker' => 'Quality hub · Emergency lighting',
            'crumb' => 'Emergency lighting',
            'h1' => 'Emergency lighting',
            'h1Accent' => 'escape routes you can still see',
            'lede' => 'Monthly function tests, an annual full-duration test, a logbook, and upgrades when the fittings no longer cover the route.',
            'honest' => 'We follow BS 5266 practice as high-level guidance. We do not invent a legal monthly visit for a two-bed single let that has no system.',
            'coverTitle' => 'Testing first, new fittings when needed',
            'cover' => [
                'If you already have emergency lighting, the file wants proof it still works. If the FRA says the escape is dark, the quote is for a design and install — not a sticker on a dead fitting.',
                'Guide: [emergency lighting testing](/pages/resources/emergency-lighting-testing). Service: [emergency lighting](/pages/services/emergency-lighting).',
            ],
            'work' => [
                'Monthly-style function tests and annual duration tests',
                'Logbook / visit records for the file',
                'LED upgrades and additional points where the route is not covered',
            ],
            'whoTitle' => 'Who needs this hub',
            'who' => [
                ['title' => 'Shared houses & blocks', 'text' => 'Common parts and protected routes that must stay usable in a power cut.'],
                ['title' => 'Workplaces', 'text' => 'Offices and industrial escapes already on a lighting schedule.'],
                ['title' => 'After an FRA', 'text' => 'The assessment said “provide / maintain emergency lighting” and you want one contractor.'],
            ],
            'relatedGuides' => ['emergency-lighting-testing', 'commercial-fire-safety-basics', 'fire-risk-assessment-guide'],
            'formService' => 'Emergency lighting',
            'formHeading' => 'Request an emergency-lighting quote',
            'formIntro' => 'Existing fittings or a new system? Say which. Photos of the escape help.',
            'formPlaceholder' => 'Building type, existing lighting?, last test date…',
            'faqs' => [
                ['q' => 'Is a torch policy enough?', 'a' => 'Sometimes for a simple workplace the FRA accepts it. Sleeping risk and public access usually will not. We will not sell fittings you do not need — or skip them when the route is blind.'],
                ['q' => 'Do you publish a per-fitting price?', 'a' => 'No. Height, wiring and access equipment change the job.'],
            ],
        ],
        'stockport-property-compliance' => [
            'navLabel' => 'Stockport',
            'pageTitle' => 'Property Compliance Stockport SK2 | Local Contractor',
            'metaDesc' => 'Property compliance in Stockport from Offerton SK2 — EICR, gas safety, FRA, fire systems and landlord files. Local yard, scoped quotes, no thin doorway clones.',
            'metaKeywords' => 'property compliance Stockport, EICR Stockport, landlord certificates Offerton SK2, FRA Stockport',
            'ogImage' => '/assets/images/services/building-maintenance.jpg',
            'kicker' => 'Quality hub · Stockport',
            'crumb' => 'Stockport',
            'h1' => 'Stockport property compliance',
            'h1Accent' => 'from the Offerton yard',
            'lede' => 'We work from 17 Woodlands Park Road, Offerton, SK2 5DE. Terrace conversions, semis and small blocks across SK1–SK3 and the Heatons are the everyday diary.',
            'honest' => 'This is one local hub with real geography — not a generated page for every Stockport street. Send the actual address when you quote.',
            'coverTitle' => 'What Stockport lets usually need',
            'cover' => [
                'Older terrace and semi conversions often show extra sockets, split boards and tenant alterations on the [EICR](/pages/electrical-safety-landlords). Gas still sits in most family lets. Shared houses add [FRA](/pages/fire-risk-assessment) and life-safety systems.',
                'GM overview: [Greater Manchester compliance](/pages/resources/greater-manchester-property-compliance). Areas index: [areas](/pages/areas).',
            ],
            'work' => [
                'Landlord certificate files for Stockport and neighbouring SK postcodes',
                'Fire and electrical work on conversions typical of the borough',
                'Short hops from SK2 — we will say if a job is outside a sensible run',
            ],
            'whoTitle' => 'Local booking patterns',
            'who' => [
                ['title' => 'Owner-landlords in the borough', 'text' => 'One or two doors, keys with a neighbour, want a single local number.'],
                ['title' => 'Agents in Stockport town', 'text' => 'Voids that cannot wait for a contractor travelling from another city.'],
                ['title' => 'Small commercial', 'text' => 'Shops and offices along the A6 corridor that need FRA and kit servicing.'],
            ],
            'relatedGuides' => ['greater-manchester-property-compliance', 'booking-compliance-certificates', 'let-ready-void-checklist'],
            'formService' => 'Stockport compliance visit',
            'formHeading' => 'Request a Stockport quote',
            'formIntro' => 'SK postcode and the jobs due. Same-week is capacity-dependent, never a promise in a headline.',
            'formPlaceholder' => 'SK postcode, property type, certificates needed…',
            'faqs' => [
                ['q' => 'Where are you based?', 'a' => '17 Woodlands Park Road, Offerton, Stockport SK2 5DE. Phone ' . PHONE . '.'],
                ['q' => 'Do you only take Stockport work?', 'a' => 'No. Manchester and the wider North West are in scope. This hub is for people searching locally.'],
            ],
        ],
        'manchester-property-compliance' => [
            'navLabel' => 'Manchester',
            'pageTitle' => 'Property Compliance Manchester | From Stockport SK2',
            'metaDesc' => 'Property compliance in Manchester — EICR, gas, FRA and fire systems from a Stockport SK2 contractor. City lets and conversions; scoped quotes, not doorway spam.',
            'metaKeywords' => 'property compliance Manchester, EICR Manchester, landlord certificates Manchester, FRA Manchester',
            'ogImage' => '/assets/images/services/commercial-fit-out.jpg',
            'kicker' => 'Quality hub · Manchester',
            'crumb' => 'Manchester',
            'h1' => 'Manchester property compliance',
            'h1Accent' => 'city lets, from SK2',
            'lede' => 'City-centre conversions, dense terraces and mixed-use blocks — attended from the Offerton yard, quoted after we know the access and the kit.',
            'honest' => 'We are not a Manchester-registered licensing authority and we do not staff a city-centre shopfront. We are a Stockport contractor who routinely works the city when the job is clear.',
            'coverTitle' => 'What Manchester stock usually throws up',
            'cover' => [
                'Basement rooms, shared kitchens and converted mill or terrace layouts change both [EICR](/pages/electrical-safety-landlords) scope and [FRA](/pages/fire-risk-assessment) precautions. Parking and concierge access change the visit, which is why there is no honest web price.',
                'Sister hub: [Stockport](/pages/stockport-property-compliance). Guide: [Greater Manchester](/pages/resources/greater-manchester-property-compliance).',
            ],
            'work' => [
                'Landlord and commercial certificates across Manchester and neighbouring boroughs',
                'Fire systems in conversions and common parts',
                'Coordinated access when a block manager holds the keys',
            ],
            'whoTitle' => 'Who books Manchester from SK2',
            'who' => [
                ['title' => 'City landlords', 'text' => 'A handful of flats, agent in town, certificates due before a Friday check-in.'],
                ['title' => 'Block managers', 'text' => 'Common-parts FRA, alarm and lighting — one contractor who will actually attend.'],
                ['title' => 'Small workplaces', 'text' => 'Offices and studios that need a current fire and electrical file.'],
            ],
            'relatedGuides' => ['greater-manchester-property-compliance', 'commercial-fire-safety-basics', 'booking-compliance-certificates'],
            'formService' => 'Manchester compliance visit',
            'formHeading' => 'Request a Manchester quote',
            'formIntro' => 'Postcode, parking / concierge notes, and the jobs due.',
            'formPlaceholder' => 'M postcode, building type, access notes, certificates needed…',
            'faqs' => [
                ['q' => 'Do you have a Manchester office?', 'a' => 'No. The yard is Offerton, Stockport SK2. Travel is built into the quote when needed.'],
                ['q' => 'Will you create a page for every Manchester ward?', 'a' => 'No. That is doorway spam. Send the address; we will tell you if we can attend.'],
            ],
        ],
        'legionella-landlords' => [
            'navLabel' => 'Legionella for landlords',
            'pageTitle' => 'Legionella Risk Assessment for Landlords | North West',
            'metaDesc' => 'Landlord Legionella risk assessment from Stockport SK2. HSE L8 / HSG274 language. Sampling only when justified. Price on application — no invented fees or lab badges.',
            'metaKeywords' => 'landlord legionella risk assessment, legionella testing landlords, water hygiene North West, Stockport legionella, Manchester legionella',
            'ogImage' => '/assets/images/services/plumbing.jpg',
            'kicker' => 'Quality hub · Water hygiene',
            'crumb' => 'Legionella for landlords',
            'h1' => 'Legionella for landlords',
            'h1Accent' => 'assessed, not a fake annual test',
            'lede' => 'A written look at the water system you actually have — then sampling only if that picture says it would help. Quoted POA from Offerton SK2.',
            'honest' => 'We do not publish a per-let fee, invent a legal “annual water test” for every terrace, or claim a named laboratory accreditation on this page. Not legal advice.',
            'coverTitle' => 'What landlords usually need written down',
            'cover' => [
                'HSE expects dutyholders to consider Legionella risk. A combi-fed house with no stored tank is often lower risk than tanks, unused en-suites or a shared system — we still write that if you ask us to assess.',
                'Service: [Legionella risk assessment](/pages/services/legionella-risk-assessment). Guide: [landlord Legionella](/pages/resources/legionella-risk-assessment). Keyword hub: [landlord Legionella RA](/pages/keywords/landlord-legionella-risk-assessment).',
            ],
            'work' => [
                'Scoped Legionella risk assessments for rented houses, flats and small shared lets',
                'Temperature, storage and little-used outlet notes for the management file',
                'Water samples only when the assessment supports them — quoted POA',
                'Commercial and block systems scoped separately when plant is more complex',
            ],
            'whoTitle' => 'Who uses this hub',
            'who' => [
                ['title' => 'Private landlords', 'text' => 'One or many doors. Want a file-ready note, not a dip-price online.'],
                ['title' => 'Letting agents', 'text' => 'Voids and renewals where the water system has tanks or little-used showers.'],
                ['title' => 'Small portfolios', 'text' => 'Several addresses in one GM cluster so travel is not the whole day.'],
            ],
            'relatedGuides' => ['let-ready-void-checklist', 'booking-compliance-certificates', 'electrical-safety-rented-homes'],
            'formService' => 'Legionella — landlord risk assessment',
            'formHeading' => 'Request a Legionella POA quote',
            'formIntro' => 'Postcode, property type and whether you have stored water. No catalogue fee.',
            'formPlaceholder' => 'Postcode, rented or commercial, tanks / unused showers, access…',
            'faqs' => [
                ['q' => 'Is this an HMO package page?', 'a' => 'No. Existing Let Ready and workplace packages stay on their own pages. We are not duplicating HMO package landings (PR #3).'],
                ['q' => 'Do you always take samples?', 'a' => 'No. Assessment comes first. Sampling is POA if recommended.'],
            ],
        ],
        'asbestos-landlords' => [
            'navLabel' => 'Asbestos for landlords',
            'pageTitle' => 'Asbestos Survey for Landlords | Duty to Manage',
            'metaDesc' => 'Landlord asbestos surveys for common parts and rented stock in the North West. CAR 2012. Management or refurbishment scoped honestly. POA. Licensed removal by others.',
            'metaKeywords' => 'landlord asbestos survey, asbestos management survey landlords, common parts asbestos Stockport Manchester, asbestos testing POA',
            'ogImage' => '/assets/images/services/building-surveys.jpg',
            'kicker' => 'Quality hub · Asbestos',
            'crumb' => 'Asbestos for landlords',
            'h1' => 'Asbestos for landlords',
            'h1Accent' => 'surveyed for the duty you actually have',
            'lede' => 'Common parts and conversions are a different duty from a purely domestic terrace. We scope management versus refurbishment, then quote POA.',
            'honest' => 'We do not claim a UKAS, BOHS or HSE licence on this page. Licensed asbestos removal is by others. No invented landlord-pack price.',
            'coverTitle' => 'Duty to manage, not a kit in the post',
            'cover' => [
                'The Control of Asbestos Regulations 2012 sit behind the duty to manage in non-domestic premises and in the common parts of many multi-occupied buildings. Describe the property; we will say what is proportionate.',
                'Service: [asbestos survey](/pages/services/asbestos-survey). Guide: [landlord asbestos](/pages/resources/asbestos-survey). Keyword hub: [landlord asbestos survey](/pages/keywords/landlord-asbestos-survey).',
            ],
            'work' => [
                'Management surveys for normal occupation and maintenance access',
                'Refurbishment surveys before opening-up, strip-out or demolition',
                'Sampling tied to rooms and materials when the scope needs it',
                'Honest inaccessible-area notes — we do not pretend voids were opened',
            ],
            'whoTitle' => 'Who commissions this',
            'who' => [
                ['title' => 'Landlords of conversions and blocks', 'text' => 'Shared halls and common parts where the duty to manage applies.'],
                ['title' => 'Agents planning works', 'text' => 'A kitchen or bathroom strip that needs the right survey type first.'],
                ['title' => 'Commercial landlords', 'text' => 'Shops, offices and industrial units — still POA after floor area and access.'],
            ],
            'relatedGuides' => ['let-ready-void-checklist', 'booking-compliance-certificates', 'commercial-fire-safety-basics'],
            'formService' => 'Asbestos — landlord survey',
            'formHeading' => 'Request an asbestos POA quote',
            'formIntro' => 'Age, floor area, access and whether walls are coming open.',
            'formPlaceholder' => 'Postcode, age, common parts or single let, planned works…',
            'faqs' => [
                ['q' => 'Is this an HMO package page?', 'a' => 'No. We are not duplicating HMO package landings from PR #3.'],
                ['q' => 'Do you remove asbestos?', 'a' => 'Licensed removal is not this service. If removal is required, appoint a suitable licensed contractor.'],
            ],
        ],
    ];
}
